server/metadata/meta_version.go, server/metadata/meta_version_test.go, server/transaction/manager.go, server/transaction/session.go, store/kv/fdb.go, store/kv/kv.go, store/kv/kv_test.go
The idea is to track the schema change using metadata version key. Using this we can implement transactional DDL APIs.
This will also be used to provide a strongly consistent Cache lookup on the schemas i.e. anytime version changes we
know that a DDL operation is performed which means we can invalidate the cache and reload from the disk.
=> Implement methods to increment/read the metadata version

deployment/manifests/base/service_grpc.yaml
A second service is needed to be able to route the HTTP and GRPC traffic correctly from the ALB based on the headers
=> [k8s] A second service is needed to be able to route the HTTP and GRPC traffic

server/metadata/encoding/dictionary.go, server/metadata/encoding/dictionary_test.go
Changing subspaces declaration from constants to variables to allow tests to run in parallel for different packages.
=> fix: small tests fixes

deployment/manifests/base/service_grpc.yaml
Reverts tigrisdata/tigrisdb#160
=> Revert "[k8s] The grpc service has to be defined as a headless service"

schema/collection_test.go, schema/schema.go, schema/schema_test.go, server/metadata/encoding/schema_test.go, server/metadata/tenant_test.go, test/v1/client/client_test.go, test/v1/server/collection_test.go, test/v1/server/document_test.go
To better comply with JSON schema standard. Updating TigrisDB schema to read the schema name from `title` attribute. (It was `name` before)
=> fix!: Updated schema to use title attribute for schema name

.github/workflows/go-test.yaml, Makefile, README.md, docker/Dockerfile, scripts/install_build_deps.sh, scripts/install_test_deps.sh, test/docker/Dockerfile, test/docker/docker-compose.yml
Unifies make targets for the various architectures and upgrades FDB to 7.1.7 to support M1 natively.
=> chore: unify make targets for architectures

server/metrics/metrics.go, server/metrics/requests.go, server/metrics/requests_test.go, server/midddleware/metrics.go, server/midddleware/metrics_test.go, server/muxer/muxer.go
Initialize all GRPC metrics with tags at server startup (on GRPC server creation).
=> feat: initialize GRPC metrics on startup

deployment/manifests/base/search-deployment.yaml, deployment/manifests/base/service_search.yaml
Adds Search to the deployment example required for `alpha.20` deployments.
=> feat: add search container to example deployment

deployment/manifests/base/service.yaml, deployment/manifests/base/service_grpc.yaml, deployment/manifests/base/service_search.yaml
This PR fixes an issue where environment variables the Tigris configuration (`spf13/viper`) collide with environment variables injected by Kubernetes for its `Service`-es.
The problem is that `spf13/viper` would expect the configuration for `Search.Port` to be of type `Int`:
https://github.com/tigrisdata/tigris/blob/d5de7997561e6a61b2d085d7abf6c43ea1a173b1/server/config/options.go#L71-L77
However, if a Kubernetes Service is deployed with the name `search` in the Tigris Server group, as outlined in our deployment example, the following environment variables will be injected in each `tigris-server` pod:
```
root@tigris-search-867c5b8d56-zr8nx:/# env | grep -i search
TIGRIS_SERVER_SEARCH_PORT_80_TCP_PORT=80
TIGRIS_SERVER_SEARCH_PORT=tcp://172.20.84.196:80 …
```
=> fix: Avoid env collisions between viper and k8s service

server/metrics/metrics.go, server/metrics/requests.go, server/metrics/requests_test.go, server/midddleware/metrics.go
Separate counters for known errors (at the Tigris GRPC and FoundationDB levels). 
Example of a metric in case of known error:
```
tigris_server_requests_specific_error_total{code="NOT_FOUND",method="Read",service="tigrisdata.v1.Tigris",source="tigris",type="stream"} 1
tigris_server_requests_unknown_error_total{method="BeginTransaction",service="tigrisdata.v1.Tigris",type="unary"} 0
```
Metrics with known errors and the tags for them are created dynamically at the time when the error is happening.
=> feat: separate specific and unknown errors, tag no known error metrics

docker/local/docker-compose.yaml
The docker compose file in local is outdated. 
The container and volume target for fdb need to be updated to work with the newer, M1 friendly image of FoundationDB.
Also, as search became a crucial component for Tigris the local compose file needs to bring the search container up as well.
=> Fix docker-compose file for local

deployment/manifests/base/server.yaml
Use the service address to communicate with search in the Kubernetes deployment example.
=> fix: use service address for search

server/metrics/metrics.go, server/metrics/requests.go, server/metrics/requests_test.go, server/midddleware/metrics.go, server/midddleware/metrics_test.go
All non-error specific counters and histograms are pre-created at the tally level.
Error specific counter's tags are pre-created, the specific error codes are part of the counter's name.
=> refactor: all tags and non-error specific counters pre created

schema/fields.go, schema/fields_test.go, schema/schema.go
- basic restriction for collection field names (language keywords not allowed and fixed pattern)
- field name can start with `[a-zA-Z_$]` and then contain zero or more `[a-zA-Z0-9_$]` 
The motivation here is to future proof various programming language's models. 
TODO
- we can allow user to disable programming language keyword restriction on field names optionally (not by default) in case if they know they are never going to work with some programming language, there is no point of restricting them for that scenario.
- Add similar restriction for collection and database name.
- Fine tune these restriction to make more tighter as we learn iteratively.
=> feat: Added basic restriction for collection field names

server/config/options.go
Removes the UNIX domain socket for tracer to let the Datadog trace agent default to environment variable based discovery. 
We should prefer containerized installations but the UNIX domain socket would be prevalent in host based installations. Note that this is simply a convenience feature and the different configuration options can still be passed explicitly as required.
I expect this change to make Kubernetes based deployments simpler where simply setting `DD_AGENT_HOST` will make the client pick up the correct target.
=> feat: better tracing defaults

server/midddleware/middleware.go
Like the title on the can says, it instruments requests after authorization and starts the tracer/profiler.
=> feat: instrument requests with profiler

server/config/config.go, server/main.go
Allows one to specify the configuration file to use with server. This makes it easy to specify custom configuration files for unique deployment scenarios.
***NOTE*** I removed an the old pflag.String() cruft that I believe was not in use. Please let me know if that's not the case! 
***SYNOPSIS***
```
$ ./server/service --help
Usage of ./server/service:
-c, --config string   server configuration file
pflag: help requested
$ ./server/service -c config/server.dev.yaml
```
=> feat: ability to specify config as an argument

.github/workflows/publish-debug-image.yaml
Adds a new workflow that will allow us to publish ad-hoc debug images for deployment validation and integration tests.
This workflow will create images if the PR is labeled with `debug image`. The resultant image will be published to `tigrisdata/tigris-debug`.
Before label:
After label:
See [DockerHub](https://hub.docker.com/repository/docker/tigrisdata/tigrisdebug) for an example image that was created during #331, triggered using the branch name.
=> feat: Add workflow for building debug images

Makefile
The linter was fixed to be more comprehensive but with the expanded run time it now times out sporadically. This PR increases its timeout to `5m` in the `Makefile`.
Last experienced the timeout on #337:
=> fix: increase linter timeout

.github/workflows/publish-debug-image.yaml, server/config/options.go, server/tracing/tracing.go
Enables code hot spots and endpoints in Datadog traces.
Individually, also fixes the push condition for publishing debug images.
=> feat: enable codehotspots and endpoints in DD tracing

scripts/install_build_deps.sh
Running make test results in a not found package error.
```
#0 7.453 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.15.0-37.39_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
#0 7.453 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Running apt-get update fixes it.
=> fix: fix make test error

server/config/config.go
The message on the tin can says it all.
=> fix: load environment during config init

server/metrics/metrics.go, server/metrics/requests.go, server/metrics/requests_test.go
Load the environment from tags, add grpc_service to grpc request metric tags.
=> fix: add grpc service name to grpc metrics

server/metrics/requests.go, server/metrics/requests_test.go, server/midddleware/metrics.go, server/midddleware/metrics_test.go, server/midddleware/middleware.go, server/muxer/muxer.go
Add namespace as part of the tags. When the metrics are initialised at server startup, those are using `default_namespace`.
Example:
```
server_requests_ok{env="",grpc_service="tigrisdata.v1.Tigris",method="ListDatabases",namespace="default_namespace",service="tigris-server",version="065426c"} 15
```
=> feat: namespace tag in grpc request metrics

server/config/options.go, server/tracing/tracing.go
Sets a default sampling rate of 1% but also makes it configurable for tracing and profiling. Logging will be tied to and implement via a separate PR.
=> feat: implement trace sampling

server/config/options.go, server/midddleware/middleware.go, util/log/log.go
Implements log sampling for request logs. When testing, note that requests logs are created 2x per request.
=> feat: implement request log sampling

server/metrics/fdb.go, server/metrics/fdb_test.go, server/metrics/metrics.go, server/metrics/requests.go, server/metrics/requests_test.go, server/midddleware/auth.go, server/midddleware/metrics.go, server/midddleware/metrics_test.go, server/midddleware/middleware.go, server/midddleware/namespace.go, server/muxer/muxer.go, server/request/request.go, server/request/request_test.go, server/services/v1/sessions.go, store/kv/kv.go, store/kv/kv_test.go
Add namespace tags to FDB metrics. The GetInternalDatabase() call (used by CDC) will always be tagged as default_namepsace.
=> feat: Add namespace tags to FDB metrics

api/server/v1/marshaler.go, server/services/v1/query_runner.go
Includes fixes for:
- null `Hits` and `Facets` to be serialized as empty JSON objects instead of null
- totalPages were having an extra page being computed in some cases (when found elements was either `0` or same as `pageSize`)
=> fix: Hits and Facets cannot be null

api/server/v1/tx.go, server/config/options.go, server/main.go, server/metadata/tenant.go, server/metadata/tenant_test.go, server/midddleware/forwarder.go, server/midddleware/validate.go, server/services/v1/api.go, server/services/v1/query_runner.go, test/v1/server/admin_test.go
By default, drop collection will be only metadata change. Setting `fdb_delete` to true will be performing fdb delete(clearrange call).
=> fix: allow enabling fdb delete using config, fix a metadata version bug

server/services/v1/search_reader.go
- Ability to request certain document fields from search results, by inclusion or exclusion:
```
{
"q": "running",
"fields": {"title": false, "price": false}
}
```
- Fixed a minor bug where facet sizes was not being respected in response. Only the max size was being honored
=> feat: field selection for search

schema/collection.go, server/services/v1/query_runner.go, server/services/v1/query_runner_test.go
Validating search request against `queryable` fields instead of schema fields.
=> fix: Allow Searching and Faceting over nested fields

server/metrics/tracing.go, server/middleware/middleware.go, server/middleware/tracing.go
Fix datadog traces, all methods are visible in datadog traces under the same operation name.
=> fix: fix datadog traces

lib/json/encoder.go, server/services/v1/search_indexer.go, server/services/v1/search_reader.go
- Use decoder instead of JSON unmarshaler to avoid default float conversion
- Use base64 encoding for bytes field during indexing.
=> fix: fixing encoding issues

api/server/v1/marshaler.go, api/server/v1/marshaler_test.go
Skip custom marshalling wherever it's not needed.
=> Fix search response marshalling

server/middleware/auth.go
- Auth is bypassed for certain methods. 
- Reading the method name from auth middleware was broken, this PR fixes it.
=> fix: Fixed the AuthBypassedMethod name reading

server/metrics/fdb.go, server/metrics/metrics.go, server/metrics/requests.go, server/metrics/search.go, server/metrics/session.go, server/metrics/size.go, server/metrics/size_test.go, server/metrics/tenant.go, server/quota/quota.go, server/services/v1/query_runner.go
* Namespace level metrics are updated on quota calculation refresh, they are not appearing if quotas are disabled.
* Database level metrics are updated on DescribeDatabase requests.
* Collections level metrics are updated on DescribeCollection requests (metrics are updated for that single collection) and on DescribeDatabase requests (metrics are updated for all collections in the database).
=> feat: Size metrics for namespace, database and collection

server/metrics/metrics.go, server/metrics/network.go, server/metrics/network_test.go, server/middleware/tracing.go
Metrics for bytes sent and received. 
Example metrics:
```
net_bytes_received{collection="users",db="sampledb",env="pboros",grpc_method="Read",grpc_service="tigrisdata.v1.Tigris",grpc_service_type="stream",service="tigris-server",tigris_tenant="default_namespace",version="dev"} 27
net_bytes_sent{collection="users",db="sampledb",env="pboros",grpc_method="Read",grpc_service="tigrisdata.v1.Tigris",grpc_service_type="stream",service="tigris-server",tigris_tenant="default_namespace",version="dev"} 195
```
=> feat: Metrics for bytes sent and bytes received on the network

api/server/v1/validator.go, schema/fields.go, test/v1/server/collection_test.go, test/v1/server/database_test.go, util/util.go
db and collection name
- it cannot contain any programming language keyword (from our curated list).
- it must consist of alphanumeric and `_`.
- it must begin with alphabet.
- It must have length atleast 1.
=> fix: Added db and collection name restriction

keys/key.go, query/filter/filter.go, query/filter/selector.go, server/config/options.go, server/services/v1/api.go, server/services/v1/query_runner.go, server/services/v1/request.go, server/services/v1/row_reader.go, server/services/v1/search_reader.go, server/services/v1/sessions.go, server/transaction/manager.go, store/kv/errors.go, store/kv/fdb.go
- Supporting read by any fields even if indexing store is disabled
- Implicit transactions now allow long-running reads
- Introduce ReadOnly Session so that implicit transactional reads do not create any transaction if reads need to happen from the indexing store. Also, moving out the search API to ReadOnlySession so that it happens without creating any transaction.
=> feat: Fallback to full table scan if indexing store is not available/disabled

lib/date/converter.go, query/filter/filter.go, schema/collection.go, schema/collection_test.go, schema/fields.go, schema/fields_test.go, server/services/v1/search_indexer.go, server/services/v1/search_indexer_test.go
Allowing filtering and sorting by metadata fields `created_at` and `updated_at`:
```json
{
"q": "",
"filter": {
"$and": [
{
"created_at": {
"$gt": "2022-08-16T17:29:28.000Z"
}
},
{
"created_at": {
"$lt": "2022-08-25T17:29:28.000Z"
}
}
]
}
}
```
=> feat: Querying on metadata fields

api/server/v1/marshaler.go, server/services/v1/observability.go, server/services/v1/observability_test.go
- TigrisOperation filter added.
- Added ability to further process the originally returned timeseries.
- Added ability to disable processing to support gauge query.
=> feat: Extended metric query API

go.mod, go.sum, server/metrics/fdb.go, server/metrics/fdb_test.go, server/metrics/network.go, server/metrics/network_test.go, server/metrics/requests.go, server/metrics/requests_test.go, server/metrics/search.go, server/metrics/search_test.go, server/metrics/session.go, server/metrics/size.go, server/metrics/tags.go, server/metrics/tags_test.go, server/metrics/tracing.go, server/metrics/tracing_test.go, server/middleware/tracing.go, server/services/v1/sessions.go, store/kv/kv.go, store/search/ts.go
Fixes panic on inconsistent metrics tags by forcing tags on each tally scope to be always the same. 
* If a tag key is missing, it's filled up with "unknown"
* If there is an extra tag key, it's removed
Added stronger testing to ensure this no longer happens.
=> fix: fix panic on inconsistent metric tags

server/metrics/auth.go, server/metrics/fdb.go, server/metrics/metrics.go, server/metrics/requests.go, server/metrics/tags.go, server/metrics/tags_test.go, server/metrics/tracing.go, server/middleware/auth.go, server/middleware/middleware.go, server/middleware/tracing.go, server/services/v1/sessions.go, store/kv/kv.go, store/search/ts.go
Initial take on authentication related metrics.
* Has the grpc_method tag
* Doesn't have tigris_tenant or any other standard tags
* Works even if authentication is turned off and measures the no-op in that case
* It creates tracing spans for authentication, but can't tie it yet to the rest of the spans. Will improve this in the future.
Fixes:
* grpc_method tags were not always propagated to child spans correctly
* on setting some tags (like env, version) only from the standardizing process led to unknown values where the value was actually known, this is fixed
=> feat: authentication related metrics

go.mod, go.sum, server/config/options.go, server/middleware/auth.go, server/middleware/auth_test.go, server/middleware/middleware.go, server/services/v1/auth.go
- Added one switch that will control if the auth middleware should be invoked or not.
- cache access token for better performance.
- validate expiration after reading from cache.
- TODO: handle key rotation
=> fix: Cache access token validation

server/metrics/metrics.go
Expose go metrics on /metrics.
Example:
```
fdb_response_time_sum{collection="unknown",db="unknown",env="pboros",fdb_method="TableSize",grpc_method="ListDatabases",grpc_service="tigrisdata.v1.Tigris",grpc_service_type="unary",service="tigris-server",tigris_tenant="default_namespace",version="dev"} 0.002893325
fdb_response_time_count{collection="unknown",db="unknown",env="pboros",fdb_method="TableSize",grpc_method="ListDatabases",grpc_service="tigrisdata.v1.Tigris",grpc_service_type="unary",service="tigris-server",tigris_tenant="default_namespace",version="dev"} 6
go_gc_duration_seconds{quantile="0"} 6.5687e-05
go_gc_duration_seconds{quantile="0.25"} 7.8915e-05
go_gc_duration_seconds{quantile="0.5"} 9.044e-05
go_gc_duration_seconds{quantile="0.75"} 0.000583164 …
```
=> feat: expose go process metrics

server/middleware/tracing.go
Increase the error counters instead of the ok counters in case of errors.
=> chore: error counters were not incremented on errors

server/metrics/requests.go, server/metrics/requests_test.go, server/middleware/auth.go, server/middleware/tracing.go, server/request/request.go, server/request/request_test.go
- consolidated RequestMetadata & RequestEndpointMetadata into RequestMetadata.
- fixed the tenant name parsing prior to authentication.
- reduced logging level to avoid flooding in case of unauthenticated requests.
=> refactor: Consolidated namespace tags parsing

query/expression/expression.go, query/expression/expression_test.go, query/filter/comparison.go, query/filter/filter.go, query/filter/filter_test.go, query/filter/selector.go, schema/collation.go, server/services/v1/key_generator.go, test/v1/server/document_test.go, value/value.go, value/value_test.go
The filters now allow passing a collation to allow case-insensitive queries like the below syntax. 
`{
"filter": {
"string_value": {
"$eq": "UPPer",
"collation": {
"case": "ci"
}
}
}
}`
=> feat: Support case sensitive/insensitive collation in filters

server/metrics/tags.go, server/metrics/tracing.go, server/middleware/metadata_extractor.go, server/middleware/middleware.go, server/middleware/tracing.go, server/quota/quota.go
* On panic, the full stack trace can to to the error tag, cutting that after the first newline
* The SendMsg and ReceiveMsg are present on the streams regardless if the interceptors are present, so they should not expect values populated by the interceptor
* More logging in quota in case of unknown tenant 
* Move namespace name extraction before authentication to it's own interceptor, so it's not dependent on tracing
=> fix: unauthenticated namespace available regardless of tracing

server/middleware/auth.go, server/middleware/auth_test.go, server/middleware/middleware.go, server/middleware/namespace.go, server/request/request.go
* Allow getAccessToken to proceed with default_namespace, when
called with app_id/app_secret credentials instead of token.
* Return and error if namespace is empty in the token
* Set namespace to "unknown" if token is not present in the request
* Set namespace to "default_namespace" if we know that token should not
be present or request is across namespaces
* Use default namespace if namespace isolation is disabled by config
=> Allow getAccessToken API without namespace set

lib/container/priority_queue.go, lib/container/priority_queue_test.go, server/search/facets.go, server/search/facets_test.go, server/search/hits.go, server/search/hits_test.go, server/services/v1/search_reader.go
- Instead of directly appending facets from multiple search queries, store them in intermediate data structure, handle duplicates and sort them in descending order before returning to user. 
- This only impacts `OR` queries and skips `FacetStats` altogether for them
- Regular search queries are not impacted by this change
=> refactor: merge and sort facets for multi-search

go.mod, go.sum, server/main.go, server/metadata/users.go, server/middleware/middleware.go, server/muxer/grpc.go, server/muxer/http.go, server/muxer/muxer.go, server/services/v1/auth.go, server/services/v1/auth_provider.go, server/services/v1/service.go, server/services/v1/user.go
- User metadata will store machine application's access token that is expiration aware.
- It will keep the metadata in sync with app rotation/deletion.
- multiple node deployment will not result in multiple external calls now.
=> feat: Added cache for auth tokens

server/metrics/auth.go, server/metrics/fdb.go, server/metrics/fdb_test.go, server/metrics/requests.go, server/metrics/search.go, server/metrics/search_test.go, server/metrics/session.go, server/metrics/session_test.go, server/metrics/tracing.go, server/metrics/tracing_test.go, server/middleware/auth.go, server/middleware/tracing.go, server/services/v1/sessions.go, store/kv/kv.go, store/search/ts.go
* Split error and not error timers, like request counters
* Timers are tied to tracing spans now (like counters)
* Simplifies tagging (timers no longer need to have separate tags)
=> feat: split error and ok response times in metrics

server/metrics/tracing.go, server/middleware/tracing.go
The top level tracing spans for streaming requests didn't have the db and collection tags (they are set in SendMsg and ReceiveMsg).
=> fix: top level spans have db and collection tag for streaming requests

server/middleware/auth.go
The RPC method was renamed from `/tigrisdata.auth.v1.Auth/getAccessToken` to `/tigrisdata.auth.v1.Auth/GetAccessToken`. And It was missed to update in bypass methods.
=> fix: Fixed the auth bypass method with RPC method rename

api/server/v1/marshaler.go, server/services/v1/observability.go, server/services/v1/observability_test.go
- Fixed the quantile processing for metrics query requests.
- Added tigris_opration:metadata to query metrics for Tigris metadata operations.
=> fix: Fixed the quantile processing for metrics query requests

server/services/v1/observability.go
When the external metrics provider returns no time series, this lack of data logging is being suppressed here to debug level.
=> fix: Reduced the log noise for lack of metric data

.github/workflows/push-docker-image.yaml
Feeds our image release process to Codefresh:
- https://g.codefresh.io/2.0/workflows/image-report-executor-2mbfw
- Extra step added to GHA: https://github.com/tigrisdata/tigris/actions/runs/3106854096/jobs/5034981542
Image reported:
- https://g.codefresh.io/2.0/images/tigrisdata%2Ftigris
=> feat: Add codefresh step to GHA

go.mod, go.sum, query/filter/selector.go, server/search/hits.go, server/search/hits_test.go, server/services/v1/search_indexer.go, server/services/v1/search_indexer_test.go, store/search/ts.go
- Read raw bytes from indexing store
- Decode data to get numerics as json.Number `json.Number`
- Validated on both read and search path:
```json
{
"documents": [
{
"id": 9223372036854775807,
"brand": "Nike",
"price": 9223372036854775800,
"review": {
"user": "zinky",
"votes": {
"upvotes": 12,
"downvotes": 9223372036854999999
}
}
}
]
}
```
```json
{
"result": {
"data": {
"id": 9223372036854775807,
"brand": "Nike",
"review": {
"votes": {
"downvotes": 9223372036854999999,
"upvotes": 12
},
"user": "zinky"
},
"price": 9223372036854775800,
},
"metadata": {
"created_at": "2022-09-22T07:08:36.170413542Z"
},
"resume_token": "TmlrZQ=="
}
}
```
```json
"hits": [
{
"data": {
"review": {
"user": "zinky",
"votes": {
"downvotes": 9223372036854999999,
"upvotes": 12
}
},
"brand": "Nike",
"id": …
```
=> fix: search and read can now display float64 without data loss

server/metrics/auth.go
The tigris_tenant tag was missing from auth metrics.
=> fix: tigris_tenant tag for auth metrics

server/metrics/auth.go, server/metrics/requests.go, server/metrics/search.go, server/metrics/session.go
Some metrics had error_code tags. The value tags are error_source and error_value.
=> fix: wrong error tag on some metrics

.github/workflows/push-docker-image.yaml
This reverts commit 9f2e9ee519c8be3da81f822a88fec422cfc998e6 and disables the Codefresh reporting step in the build.
=> fix: disable codefresh step in build

server/services/v1/auth_provider.go
List apps API returned apps created by the current user across all tenant. This PR restricts it to only return apps created by the current user in current tenant.
=> fix: List apps for current user for the current tenant

lib/container/set.go, schema/collection.go, schema/collection_test.go, schema/fields.go, schema/schema.go, schema/schema_test.go, server/services/v1/conversion.go, server/services/v1/conversion_test.go, server/services/v1/query_runner.go, test/v1/server/document_test.go, test/v1/server/integration_test.go
- The schema validation for these numbers will still be performed as an integer. 
- This allows us to support language clients in JavaScript and TypeScript where bigInt is getting serialized as a string and the caller needs to send a big integer as a string on the wire.
=> feat: Allow receiving big integer(int64) values as string as well

.github/workflows/push-docker-image.yaml, .github/workflows/push-docker-local-image.yaml
We build Docker images twice:
* on release
* on push
It's not guaranteed which one finishes first, so "on push" may overwrite the image from "on release" leading to wrong "tigris server version" output, so as release tag is not available on push.
=> Do not build Docker images on pushing to release branch

server/middleware/middleware.go
Metrics interceptor was only dependent on tracing config.
=> chore: metrics interceptor was only dependent on tracing config

api/server/v1/tx.go, errors/errors.go, go.mod, go.sum, server/config/options.go, server/metrics/datadog.go, server/metrics/quota.go, server/middleware/auth.go, server/middleware/measure.go, server/middleware/namespace.go, server/middleware/quota.go, server/quota/datadog.go, server/quota/limiter.go, server/quota/namespace.go, server/quota/namespace_test.go, server/quota/node.go, server/quota/quota.go, server/quota/storage.go, server/request/request.go, server/request/request_test.go, server/services/v1/observability.go
* Allow blacklisting of namespaces
* Optionally limited default_namespace
* Attach retry info to rate errors
* Fix Datadog connection
* Return throttling statistics in quota usage API
* Return non-retriable error if request hard limit exceeded
* Properly categorize observability, management and admin APIs
* Other bugfixes and refactoring
* Exclude DropDatabase/DropCollection from storage quota checking
=> Quota fixes

server/metadata/dictionary.go, server/metadata/dictionary_test.go, server/metadata/key_encoder_test.go, server/metadata/tenant.go, server/metadata/tenant_test.go, server/metadata/tenant_tracker.go, server/services/v1/management.go, test/v1/server/management_test.go
Namespace object has been refactored as follows:
api to internal mapping:
- `id` --> `strId`
- `code` --> `id`
- `name` --> `name`
internal refactor:
- Renamed `name` --> `strId`.
- Renamed `displayName` --> `name`.
=> refactor: Simplified namespace API

server/request/request.go, server/request/request_test.go
Machine user's token doesn't contain the key `"https://tigris/u"` at the top level in payload.
=> fix: Fixed the user type detection

api/server/v1/tx.go, server/request/request.go, server/services/v1/management.go
Get details for all namespaces in the form of:
```
{
"ns1": {
"db1": {
"coll1": {
"schema": {},
"size": x,  
}
},
"db2": {
...
}
},
"ns2": {}
}
```
=> feat: endpoint to get details for all namespaces

errors/errors.go, server/services/v1/health.go, server/services/v1/service.go
This adds a check to read the FDB metadata version read in the health check. This will make sure the server and fdb are healthy. 
Close #168
=> feat: Add fdb metadata version read in health check

.github/workflows/cli-test.yaml, .github/workflows/go-test.yaml
Only run tests on push to non-release branches.
Tests on release branches trigerred by release workflow.
=> Fix test workflow runs

server/metrics/measurement.go, server/middleware/auth.go, server/middleware/measure.go, server/middleware/metadata_extractor.go, server/middleware/namespace.go, server/quota/namespace_test.go, server/quota/storage.go, server/request/request.go
Example: 
```
requests_count_ok{collection="coll_1",db="db111333",env="test",grpc_method="CreateOrUpdateCollection",read_type="unknown",search_type="unknown",service="tigris-server",sort="unknown",tigris_tenant="default_namespace",tigris_tenant_name="default_namespace_default_namespace",version="76dfa31",write_type="unknown"} 1
```
=> fix: tigris_tenant_name displayed incorrectly for some metrics

server/metrics/measurement.go
Moving measurement logging to trace, as these are mostly used with local development. In the dev system, this spams the live tail of the debug log, so it's hard to use with this and provides very little value in that scenario.
=> chore: measurement logs should be trace

server/metrics/measurement.go, server/middleware/measure.go
The db, collection and network tags were re-calculated for every document in the result of a read request unnecessarily. This PR fixes that. Yesterday's fix also broke the db and collection name reporting for reads, fixed that as well.
=> fix: set db, collection and network tags only once for stream requests

server/metrics/measurement.go, server/middleware/measure.go
Calculate db and collection tagging only once.
=> fix: calculate db and collection tags only once for streaming requests

server/services/v1/api.go, server/services/v1/auth/auth0.go, server/services/v1/auth/noop.go, server/services/v1/auth/provider.go
This PR will delete app-keys associated with project when project is undergoing deletion.
=> fix: Delete app keys associated with project while deleting project

go.mod, go.sum, server/metadata/key_encoder.go, server/services/v1/api.go, server/services/v1/auth/auth0.go, server/services/v1/database/key_generator.go, server/services/v1/database/mutator.go, server/services/v1/database/mutator_test.go, server/services/v1/database/query_runner.go, server/services/v1/database/query_runner_test.go, server/services/v1/database/request.go, server/services/v1/database/row_reader.go, server/services/v1/database/search_indexer.go, server/services/v1/database/search_indexer_test.go, server/services/v1/database/search_reader.go, server/services/v1/database/sessions.go, server/services/v1/database/sessions_test.go, server/services/v1/database/tx_listener.go, server/services/v1/realtime.go, server/services/v1/realtime/request.go, server/services/v1/service.go
- Database core logic is moved to the database package
- Realtime core logic will be in real-time package
- The v1 package will have top-level files for service implementation like `api.go` for database APIs, `realtime.go`, for real-time APIs. 
- Also refactoring the HTTP paths that we added for muxer to enforce strictness and to have real-time as well in the path.
=> feat: Basic Realtime API stubs, separating realtime, database core logic

util/log/log.go
Move error details from the attached error field to the log message itself.
=> Fix error messages

server/metrics/measurement.go, server/metrics/tags.go, server/metrics/tags_test.go, server/middleware/auth.go, server/middleware/measure.go, server/services/v1/database/sessions.go, store/kv/kv.go, store/search/ts.go
Return unknown error_source and error_value tags for errors that have an unknown source, instead of trying to figure them out from the error itself.
=> fix: remove specific error values from unknown error sources

docker/Dockerfile.local, docker/service-local.sh
The tigris-local image is failing to start sporadically. The reason for that is tigris starts in the container before typesense is ready, and it can't connect to it. 
With this change, we will wait for foundationdb and typesense to be ready before starting the tigris server.
=> fix: local image failing to start sporadically

errors/errors_ws.go, internal/cache.go, internal/data.proto, server/services/v1/realtime.go, server/services/v1/realtime/channel.go, server/services/v1/realtime/channel_test.go, server/services/v1/realtime/device_session.go, server/services/v1/realtime/factory.go, server/services/v1/realtime/factory_test.go, server/services/v1/realtime/heartbeat.go, server/services/v1/realtime/pusher.go, server/services/v1/realtime/response.go, server/services/v1/realtime/serialization.go, server/services/v1/realtime/sessions.go, server/services/v1/realtime/types.go, server/services/v1/realtime/watcher.go, server/services/v1/realtime/watcher_test.go, store/cache/cache.go, store/cache/store.go, store/cache/stream.go, store/cache/stream_test.go
This diff is implementing core WebSocket protocol to support real-time event passing using Channels i.e. a functionality where Tigris is responsible for broadcasting events to connected devices/clients at low latency. The events will be stored in the in-memory cache during the lifetime of a channel.
The diff has the following things implemented,
- Websocket protocol to handle events 
- Disconnect
- Subscribe
- Message
- Heartbeat
- A session manager to manage device sessions
- A real-time server accepting WebSocket requests.
- Logic to manage the lifecycle of a channel, device, and stream.
- Logic to reload channels during restart, and reconnect devices back to the channel if they join in a short window.
=> feat: Core realtime functionality

docker/service-local.sh, server/config/options.go, server/main.go, server/muxer/http.go, server/muxer/muxer.go, server/services/v1/realtime.go, server/services/v1/realtime/runner.go, server/services/v1/realtime/sessions.go, server/services/v1/realtime/types.go, test/docker/docker-compose.yml
Staging on top of this PR: https://github.com/tigrisdata/tigris/pull/692
This diff implements HTTP APIs for real-time functionality. The HTTP APIs that we would be supporting will be
- GetRTChannel: To get information about the real-time channel
- GetRTChannels: To get information about all the real-time channels
- ReadMessages: To read messages from a position, the default would be read from now().
- Messages: To publish messages to a channel
- ListSubscriptions: A subscription list includes devices that are attached to the channel.
The real-time will be running on its own container using the same binary as the server but the server type will be realtime.
=> feat: Realtime HTTP APIs

api/server/v1/realtime.go, server/middleware/http.go, server/muxer/http.go, server/request/request.go
For real-time, we need HTTP Middleware. This diff is adding two:
- Auth: which is the same as the database but making it generic so that can be used for real-time as well
- Metadata: Request metadata that needed to be set in the context
=> feat: Adding a few realtime HTTP Middlewares

docker/service-local.sh
On ferretdb's CI typesense fails to start sporadically. The reason is it receives a request before it's ready to serve requests. This means that tigris server will fail to initialize.
=> fix: typesense failed to start in single image container sporadically

server/services/v1/database/mutator.go
Missing a return when the field is an integer and the actual type is not a string.
=> fix: Handling of conversion of str to int in case of wrong type

test/docker/docker-compose.yml
I incorrectly added a dependency on the `tigris_cache` for the `tigris_server2`. This isn't needed
since the `tigris_server`  has `tigris_cache` as a `depends_on`
`make run` should load up `tigris_cache`
clean up from #697
=> chore: remove tigris_cache depends_on

internal/cache.go, internal/data.go, internal/data.proto, server/cdc/listener.go, server/services/v1/realtime/channel_test.go, server/services/v1/realtime/device_session.go, server/services/v1/realtime/pusher.go, server/services/v1/realtime/request.go, server/services/v1/realtime/runner.go, server/services/v1/realtime/serialization.go, server/services/v1/realtime/types.go, store/cache/stream_test.go
To store encoding information about how the user data is encoded
Sending requests from websocket and reading channel data through HTTP APIs should work as expected
=> fix: encoding information in stream data

test/v1/server/cache_test.go
- Added `kv` in HTTP path to allow extension for other cache datatypes.
- Tests are updated to follow this new paths.
=> refactor: Refactored cache API http paths

query/update/operator.go, query/update/operator_test.go, server/services/v1/database/query_runner.go, server/services/v1/realtime/pusher.go, server/services/v1/realtime/serialization.go, test/v1/server/document_test.go
This allows modifying primary key values. In case values are modified then we need to remove the old row and add a new row.
=> fix: support mutating primary keys as part of Update request

server/services/v1/api.go, server/services/v1/cache/request.go, server/services/v1/cache/runner.go, server/services/v1/cache/sessions.go, server/services/v1/database/query_runner.go, server/services/v1/database/sessions.go, server/services/v1/realtime/runner.go, server/services/v1/realtime/sessions.go
No need to allocate req/resp object on the heap as the lifetime is tied to a request therefore allocation on the stack here will be fast and cheap.
=> refactor: Reduce allocation on heap and leverage stack by passing as value the Req/Resp objects

server/metadata/database.go, server/metadata/errors.go, server/metadata/key_encoder_test.go, server/metadata/namespaces.go, server/metadata/namespaces_test.go, server/metadata/tenant.go, server/metadata/tenant_test.go, server/quota/quota_test.go, server/quota/storage.go, server/quota/storage_test.go, server/services/v1/api.go, server/services/v1/cache/errors.go, server/services/v1/cache/runner.go, server/services/v1/database/query_runner.go, server/services/v1/management.go, server/services/v1/realtime/device_session.go, server/services/v1/realtime/errors.go, server/services/v1/realtime/runner.go
This allows wrapping up all the entities that belong to a single project in a single object. This gives the added flexibility of adding Caches/Indexes to this project object.
=> refactor: Introduce project abstraction in tenant

server/config/options.go
The FdbHardDrop configuration option tells if the range should be cleared in FoundationDB after drop database/drop collection. If this is not enabled, drops are soft delete.
During some benchmarks, we saw that hard deletes have little performance impact. 
TIG-946
=> chore: make fdb hard drop the default

schema/collection.go, schema/collection_test.go
Allow nulls when format is int32/int64
=> fix: Allow null when format is int32/int64

api/server/v1/cache.go, server/config/options.go, server/services/v1/cache.go, server/services/v1/cache/request.go, server/services/v1/cache/runner.go, store/cache/cache.go, store/cache/cache_test.go, store/cache/store.go, test/v1/server/cache_test.go
- Implementation of https://github.com/tigrisdata/tigris-api/pull/193 - keys response for cache api is made streaming.
- Implementation of https://github.com/tigrisdata/tigris-api/pull/194 - removed `kv` from path with the intent to keep all cache related operations in same HTTP path space.
Added unit test, integration test and tested manually.
=> feat: Stream the keys response

api/server/v1/marshaler.go, schema/collection.go
- Some APIs were not receiving the branch name
=> fix: Get the branch name where custom unmarshaler are used

schema/collection.go, schema/migration.go, schema/migration_test.go, schema/schema_test.go
Implemented functionality to lookup the history of incompatible
schema changes of individual collection fields.
This is needed for secondary indexes versioning.
=> Build per field schema version lookup structure

schema/migration.go, schema/rules.go, schema/rules_test.go, schema/search.go, server/metadata/key_encoder.go, server/metadata/tenant.go, server/metadata/tenant_test.go, server/services/v1/search/runner.go
The following are the schema rules that will be applied for index upgrades,
- Adding/Dropping a field is allowed.
- Changing the type of the field is not allowed.
- Changing the index source i.e. if it is backed by Tigris then it is not allowed to change for now.
=> feat: Backward compatibility rules and checks for search indexes

schema/lang/go_test.go, schema/lang/java_test.go, schema/lang/schema.go, schema/lang/schema_test.go, schema/lang/typescript_test.go, templates/schema/go/object.gotmpl
Broken:
```
createdAtmaxLength:100
```
Fixed:
```
createdAt,maxLength:100
```
=> Fix maxLength tags separator in Golang generated schema

query/filter/filter.go, query/filter/logical.go, query/filter/selector.go, server/services/v1/database/query_runner.go, test/v1/server/document_test.go, value/value.go
- A filter can be passed to query null values `'{"filter": {"field":null}}'` or empty quoted string `'{"filter": {"str":""}}'`
- Allowing querying for bytes field which is not indexed, this is performed using full table scan. 
- Allow scientific notation in the filter.
=> fix: Support query for nulls and non-indexed fields

store/search/ts.go
Allow returning more results if the prefix matches more number of documents.
=> fix: bump up default max candidates limit to 100

server/services/v1/database/query_runner.go
When user is passing search fields to query we just need to check if the field is indexed.
=> fix: Check on index, not on search field type

schema/collection.go, schema/reserved.go, schema/reserved_test.go, schema/search.go, schema/search_test.go, server/services/v1/database/search_indexer.go, server/services/v1/database/search_indexer_test.go, test/v1/server/document_test.go
This change will allow users to have `created_at/updated_at` field in the model. After this is deployed, the internal timestamps will be indexed using `_tigris_` prefix.
=> fix: Change internal fields to _tigris prefix

test/docker/docker-compose.yml
Upgrading tigris-search typesense image to 0.24.0
`image: typesense/typesense:0.23.1` -> `image: typesense/typesense:0.24.0`
[TIG-1012](https://tigrisdata.atlassian.net/browse/TIG-1012)
[TIG-1012]: https://tigrisdata.atlassian.net/browse/TIG-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade Typesense to 0.24.0

scripts/install_local_docker_deps.sh
We also need to define the new typesense image version in `scripts/install_local_docker_deps.sh`
=> Bump up ts to 0.24

query/update/operator.go, query/update/operator_test.go, server/middleware/auth.go, server/services/v1/database/query_runner.go, server/services/v1/database/search_indexer.go, server/services/v1/database/search_indexer_test.go, test/v1/server/document_test.go
When an update request is for an object, then we need to cleanup flattened obj keys that are not part of the update from Search.
=> fix: Remove keys from search if update operation is for an object

query/filter/selector.go, value/value.go
This allows querying using empty quotes, plus also adding a check so that querying on special characters also works.
=> fix: Query using empty string quotes

server/transaction/manager.go, store/kv/base.go, store/kv/fdb.go, store/kv/kv.go, store/kv/kv_test.go, store/kv/noop_store.go
Adds api to read, range, and update atomic values in the KV store. Based on the FDB docs, the value is LittleEndian encoded before being written to FDB.
This is the first PR as part of the secondary indexes work. We use the atomic values to keep track of the size of the index and the number of rows.
Closes #789
=> feat: Add KV Atomic Add/Read/ReadRange

.github/workflows/go-test.yaml, scripts/install_go.sh
Separate test action log output into multiple steps,
in order to simplify spotting the failure:
* Warmup tests
This step hides useless deps installation and docker pull logs
* Run tests
This step contains useful logs and should be checked on tests failure.
* Server logs
This step is executed on "Run tests" step failure and can be used
for deeper debugging of the failure.
* Check tests status
This step fails the action if "Run tests" is not successful
This diff also updates Go installation scripts to use v1.20
The tigrisdata/tigris-build-base docker image has been updated to
include Go 1.20 too.
=> Separate logs dump on tests failure into own step

server/metadata/namespace.go, server/metadata/namespace_test.go, server/metadata/user_test.go, server/services/v1/auth/auth0.go, server/services/v1/namespace_metadata_provider.go, server/services/v1/user_metadata_provider.go
* New project should always have corresponding metadata. This fixes the project which were created before metadata were introduced. (Are there such projects?)
* Handle ErrNotFound instead of relying on `nil, nil` in access token metadata processing.
* Return specific error to outside API callers.
=> Fix handling non existing metadata

api/server/v1/validator.go, query/filter/selector.go, schema/fields_test.go, server/middleware/measure.go, server/services/v1/database/errors.go, server/services/v1/database/query_runner.go, store/search/ts.go, value/value.go
1. This is fixing the floating point handling when the value can’t fit in 32-bit. The underlying indexing store is parsing the floating values in float(32bit) which means there are two problems:
- The smallest floating point normal number needed to be less than ~ 1.1755e-38
- The number has to be in the range -3.4e38/3.4e38
Outside of this range, an error is returned that was getting swallowed, resulting in empty documents returned for that query. I am fixing that and also handling queries for 64-bit floating-point numbers. 
2. This diff is also allowing collection names to start with `_`
=> fix: Handle floating point greater than 32 bit properly

server/request/request.go
JWT's payload part is base64 encoded. Decoding the payload after validation fails to decode with just RawStdEncoding's decode - This PR attempts to  fallback to StdEncoding decoding if the RawStdEncoding's decoder fails.
=> fix: Switched to RawStdEncoding base64 decoding

server/request/request.go, server/request/request_test.go
As part of request processing for metrics, Tigris parses the jwt payload. There are some "cached" tokens which still needs to be supported for the migration. This PR takes care of it.
=> fix: To read namespace also support backward schema for metrics

schema/fields.go, schema/rules.go, schema/search.go, server/metadata/tenant.go
During reload/restart, index building should always succeed if validation has happened during index creation time. This needs to be logged but we need to continue loading other indexes.
=> fix: Log error only if during restart index reloading schema fails

internal/data.go, schema/collection.go, server/config/options.go, server/metadata/key_encoder.go, server/metadata/tenant.go, server/services/v1/database/base_runner.go, server/services/v1/database/query_runner.go, server/services/v1/database/search_indexer.go, server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, test/docker/docker-compose.yml, test/v1/server/document_test.go
chore: Enable secondary index writes for tests
fix: Ignore missing fields for arrrays fields
fix: Refactor the way the iterator was chosen for reading the docs.
There was a subtle bug because the variables were declared at the top.
fix: Add a separate table for secondary indexes so that it doesn't
interfere with scanning the primary key index and none of the index
writes get sent to the search indexer
=> fixes for secondary indexes and integration tests

server/services/v1/auth/provider.go
Certain API calls to auth0 from Tigris are timing out. Supplying a custom HTTP client with 30s timeout to temporarily heal the issue.
As for the solution - we are replacing the backend for app keys with tigrisdata/gotrue
=> fix: Increased the timeout of auth0 calls to 30s

schema/fields.go, server/middleware/timeout.go, server/services/v1/database/errors.go, server/services/v1/database/import_runner.go, server/services/v1/database/query_runner.go, server/services/v1/database/sessions.go, server/services/v1/search/runner.go, store/kv/errors.go, store/kv/fdb.go
- Convert storage errors to HTTP errors
- Bump up default timeout to 10 seconds and maximum to 30 seconds
- Search indexes checks if numeric fields are used for full-text search and reject an error.
- Improve context deadline error messages
Fix error handling, timeouts, not leaking FDB error codes, etc
=> fix: Fix error handling, timeouts, not leaking FDB error codes, etc

schema/lang/go_test.go, schema/lang/java_test.go, schema/lang/schema.go, schema/lang/schema_test.go, schema/lang/typescript_test.go
This fixes the issue where multiple subtypes with the same name for different or identical subobjects were produced.
Now for identical subtypes, no duplicates are produced. For different subtypes with the same name, we append the name with sequential suffix.
=> Fix duplicate types in generated schema

api/server/v1/error.go, api/server/v1/marshaler.go, api/server/v1/marshaler_test.go, api/server/v1/search.go, errors/errors.go, server/search/sorted_hits.go, server/services/v1/database/errors.go, server/services/v1/search/errors.go, server/services/v1/search/reader.go, server/services/v1/search/runner.go, server/services/v1/search/session.go
- Returning a matched fields information for search response i.e. how many fields matched the search
- Individual document matched results now also return which for which field search matched that document
- Fixing search metadata errors and wrapping up in the HTTP errors.
=> feat: Add search field match information in response

server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, server/transaction/manager.go, store/kv/fdb.go, store/kv/kv.go, store/kv/noop_store.go
Replace the atomic size with `GetRangeSizeEstimate` and the count is a full table scan. The atomic updates are making the updates a lot slower. Changing that to use the `GetRangeSizeEstimate`. 
I've kept the index count in, this would be very slow in a large index but useful for unit tests and integration tests. I don't think we would expose the index count to the user. 
All tests should pass. 
Fixes #874
=> fix: Change size and count in secondary indexes

api/server/v1/search.go, query/search/group_by.go, query/search/search.go, server/search/factory.go, server/search/group.go, server/services/v1/search/reader.go, server/services/v1/search/runner.go, store/search/ts.go, test/v1/server/search_test.go
This functionality allows grouping of search results. For instance, let's say grouping needs to be done on city field. Then following is the example of the query and response. 
```
{
"q": "text",
"group_by": {
"fields": ["city"]
},
"sort": [{
"created_at": "$asc"
}]
}
```
Response:
```
{
"result": {
"hits": [],
"facets": {},
"meta": {},
"group": [{
"group_keys": [
"Anaheim"
],
"hits": [{
"data": {
"id": "2b1fd919-c752-45f8-bbe5-bb9e2f85af74"
},
"metadata": {}
}]
}]
}
}
```
https://github.com/tigrisdata/tigris/issues/885
=> feat: Add group by functionality for search index results

config/server.dev.yaml, query/filter/filter.go, query/filter/logical.go, query/filter/selector.go, schema/collection.go, schema/fields.go, schema/fields_test.go, schema/rules.go, schema/rules_test.go, schema/search.go, server/services/v1/database/base_runner.go, server/services/v1/database/query_runner.go, server/services/v1/database/search_runner.go, server/services/v1/database/secondary_index_reader.go, server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, server/services/v1/search/runner.go, test/v1/server/document_test.go, test/v1/server/integration_test.go
Secondary indexes are now configurable via the schema. Adding `index: true` to a top level field will add that field to the secondary index. The schema rules have been updated to make sure that only top level fields can be indexed.
All tests should pass. I've updated some of the update and delete test's so that the queries will use the secondary index
Fixes #875
=> feat: Configure which fields to add to index

schema/search_test.go, server/services/v1/database/secondary_indexer_test.go
This test is quite flaky because size is an estimate. And at the smaller size it isn't that accurate. 
The test just needs to prove that we have some kind of size value. 
=> chore: lower value on flaky size test

server/muxer/grpc.go
Bump grpc max receive message limit to 16MB
=> feat: Bump grpc max receive message limit to 16MB

.github/workflows/push-docker-image.yaml
Modified `/metadata-action` and added Quay.io login in our `build-and-push-image` workflow so We will push images to Quay.io registry as well.
The modified check ran for this PR.
=> Push to quay.io as well

query/filter/selector.go
We logging an error that is acceptable. There will be cases when the field we looking for does not exist in the
document or in the json timestamp object when we do a query. In those cases rather check first the field does not exist and return false. Only if it is an unexpected error do we log it. 
Test should pass
=> fix: only log unexpected errors in match

server/services/v1/auth/gotrue.go, test/v1/server/auth_test.go
When auth fails at gotrue with invalid client credentials, with this fix - proper error code and message will be returned back to user.
Added integration test.
=> fix: Fixed the error status code in case of auth failure

.github/workflows/publish-debug-image.yaml, .github/workflows/push-docker-image.yaml
Modified the build to push debug `tigris-debug` image to Quay.io in addition to DockerHub, as we intend to serve all deployments from Quay.io
Added `debug image` label to run the `push-debug-image` job.
=> Push tigris-debug to Quay.io as well

server/services/v1/auth/gotrue.go, test/v1/server/auth_test.go, test/v1/server/document_test.go
This PR sends a filter to gotrue asking to filter app keys on a project. This fixes the issue where all the app keys created by a users in a given namespaces are listed (ignoring project).
Added integration test.
=> fix: List app keys by tigris project

api/server/v1/marshaler.go, test/v1/server/auth_test.go
When there are no keys present for the scope of the call. Tigris returns `{}` empty JSON object. This PR fixes it and returns `app_keys` with `[]` empty array.
Added test for it.
=> fix: Fixed the empty keys response

server/services/v1/auth/gotrue.go, test/v1/server/auth_test.go
Gotrue response contains `created_at` in form of string (RFC3339 formatted time) at the top level in user model. This PR fixes parsing of createdAt field into Tigris's response. Also this PR abstracts out the detail in error messages from user.
Modified existing test to inspect `createdAt` field.
=> fix: Fixed parsing of createdAt field from gotrue response

api/server/v1/marshaler.go, test/v1/server/auth_test.go
Reverting the change in response behavior: While listing app keys if the response is empty - it will now skip `app_keys` key from returned JSON response. 
updated test to match this behavior
=> fix: Revert empty array response when app keys are empty for list call

server/metadata/queue.go, server/metadata/queue_test.go, server/metadata/subscope_registry.go
Adds a background queue table and api to enqueue, peak, dequeue and complete items in the queue.
The queue using vesting time which is current time plus delay time to hide items that are not ready to be worked on or are currently being worked on.
Tests should all pass
Closes #910
=> feat: Add background queue api

server/request/request.go
Metrics will use the value "unknown" for a tag that is present on the time series, but not known. This "unknown" string is later looked up as a tenant, but not found. In the phase of creating request metadata, the namespace tag will just have the value "unknown", but the lookup of the tenant will be skipped after this patch.
Fixes triggering an unnecessary error message for requests with an unknown tenant.
TIG-1162
=> fix: looking up unknown namespace triggered an error

server/services/v1/auth/gotrue.go, test/v1/server/auth_test.go
Generated client credentials contained special characters causing issues in application space (for example .env for node runtime variable substitution). Updated character set to avoid this issue.
=> fix: Updated characters for client credentials

internal/data.go, internal/data.proto, server/config/options.go, server/services/v1/database/secondary_indexer.go, server/transaction/manager.go, store/kv/chunk.go, store/kv/chunk_test.go, store/kv/fdb.go, store/kv/kv_store.go
FoundationDB only allows a maximum value size of 100KB. This diff is adding the functionality to have a layer that splits the value into multiple chunks and then store it in the underlying engine and similarly during reads merge these values back and return a single payload to the caller. This functionality is not tied to FDB directly but provide a generic mechanism to chunk and merge. 
This is not currently enabled. The following diffs will hook this class to actually start using it. The first step will be to do it for search indexes.
=> feat: Implement chunker to split/merge the data to support bigger payloads

server/metadata/queue_test.go
Removes a flaky queue API test. This test is not needed.
=> fix: remove flaky queue test

api/server/v1/header.go, go.mod, go.sum, internal/data.go, server/config/options.go, server/main.go, server/metadata/key_encoder.go, server/metadata/tenant.go, server/muxer/muxer.go, server/request/request.go, server/services/v1/database/query_runner.go, server/services/v1/search.go, server/services/v1/search/runner.go, server/services/v1/service.go, store/kv/chunk.go, store/kv/chunk_test.go, store/kv/measure.go, test/v1/server/document.go, test/v1/server/search_test.go
This diff enables to have FoundationDB as the source of truth for the indexed data. This improves the reliability story of search indexes. As the search index document size can easily be greater than 100kb therefore this diff also enabling chunking for search indexes. 
There are two knobs to control this behavior,
- storage_enabled: This is enabled as part of this diff. If this is true then the write request to search will also write to FDB. 
- chunking: This is also enabled as part of this diff for search. This means any value greater than 100kb will be chunked.
=> feat: Persist search indexes in foundationDB to have faster recovery in case of DR

.codecov.yml
* Wait for all tests to finish before sending coverage notification.
* Set coverage bounds.
=> Codecov config

util/util.go, util/util_test.go
While unflatting the object, if the input map contains structure like this
"one" --> nil
"one.two" --> "v1"
then the method tries to access `nil` as the `map` and tries to insert ("two" in this case) into it and results into the error. This PR fixes that case. 
Added test case.
=> fix: Fix unflatting object util method

value/value.go, value/value_test.go
We were using "IEEE 754 binary representation" for floating point comparison but we were not handling positive to negative floating number comparison i.e.  
- Both numbers are positive - will work fine
- Both numbers are negative - will work fine
- Breaks when one number is negative and the other is positive and vice versa. Similarly, it will break when comparing zeros and negative numbers
**Solution**: Offloading this logic to math/big which has a Float class that represents a multi-precision floating point number. This object comes with a compare API.
=> fix: Handle negative floating point comparison

schema/factory_builder.go, schema/fields.go, schema/rules.go, schema/schema_test.go, test/v1/server/document_test.go, util/util.go
Allow define field type as array, without specifying the type of array elements.
This allow to persist empty arrays.
Element types can be specified later, and is a compatible schema schema change.
Additionally: Fix UnflatMap case where nil value may come after map has been created for the object already.
=> Allow persisting arrays with incomplete schema

config/server.test.yaml, server/config/options.go, server/middleware/auth.go, test/docker/docker-compose.yml
Moving the shared secret into gotrue config. This was motivated by limitation in deployment system's config rendering support.
Updated tests with this mechanism.
=> fix: Move shared secret to Gotrue struct

api/server/v1/header.go, api/server/v1/marshaler.go, server/request/request.go, server/services/v1/database/query_runner.go, test/v1/client/client_test.go, test/v1/server/document_test.go
The client can choose to pass the "**Accept**" header with the string "**application/json**" when they want to consume the `JSON` format instead of `NDJSON` for read response. 
The default behavior with no "accept" header is still `ndjson`.
**Default**:
```
~ curl -XPOST 'localhost:8081/v1/projects/p1/database/collections/c1/documents/read' -d '{ "filter": {}}' | jq .
{
"result": {
"data": {
"addr": "aa",
"balance": 1.3,
"num": 1
},
"metadata": {
"created_at": "2023-03-27T03:33:00.277006Z"
},
"resume_token": "ZGF0YQAAAAEAAAAQAAAAEQEA/wD/AP8SAAJhYQAVAQ=="
}
}
{
"result": {
"data": {
"addr": "aa",
"balance": 1.3,
"num": 2
},
"metadata": {
"created_at": "2023-03-27T03:32:53.126956Z"
},
"resume_token": "ZGF0YQAAAAEAAAAQAAAAEQEA/wD/AP8SAAJhYQAVAg=="
}
}
{
"result": {
"data": {
"addr": "bb", …
```
=> feat: Support Accept header to stream application/json for read queries

schema/collection.go, schema/fields.go, schema/rules.go, schema/schema.go, schema/schema_test.go, server/metadata/collection.go, server/metadata/collection_test.go, server/metadata/dictionary.go, server/metadata/dictionary_test.go, server/metadata/primary_index.go, server/metadata/primary_index_test.go, server/metadata/queue.go, server/metadata/tenant.go, server/metadata/tenant_test.go, server/services/v1/database/base_runner.go, server/services/v1/database/query_runner.go, server/services/v1/database/secondary_index_reader.go, server/services/v1/database/secondary_indexer.go, store/search/search.go
Manage the state of secondary indexes in the collections metadata. Secondary indexes can be in 4 states:
1. UNKNOWN = Have not fetched the index metadata yet so the state is unknown
2. NOT_INDEXED = field is not indexed
3. INDEX_WRITE_MODE = index is being built in the background and cannot be used for queries
4. INDEX_ACTIVE = index can be used for queries
This allows Tigris to only use active and up to date indexes for querying.
There is also code clean up to differentiate between the primary key and the secondary index. The primary key index is kept in its own metadata subspace.
closes #912
=> feat: Manage secondary indexes via metadata

server/config/options.go, server/main.go, server/metadata/namespace.go, server/metrics/global_status.go, server/metrics/global_status_test.go, server/metrics/measurement.go, server/metrics/metrics.go, server/metrics/requests.go, server/metrics/units.go, server/metrics/units_test.go, server/middleware/measure.go, server/services/v1/billing/metronome.go, server/services/v1/database/collection_runner.go, server/services/v1/database/database_runner.go, server/services/v1/database/measure.go, server/services/v1/database/measure_test.go, server/services/v1/database/query_runner.go, server/services/v1/database/row_reader.go, server/services/v1/database/secondary_indexer.go, store/kv/fdb.go, store/kv/kv_store.go, store/kv/listener.go, store/kv/measure.go
Report usage based metrics as read and write units. It reports metrics through global status (caller needs to flush it on sending it to 3rd party service), it also exposes the same metrics through the `/metrics` endpoint. 
Have some traffic on the databases and check `/metrics`, tests are added as well.
#918
=> feat: report usage based metrics

server/services/v1/billing/metronome.go, server/services/v1/billing/metronome_test.go
- If billing start day is next day, today's usage won't be accounted for
- Unit tests
=> fix: Billing start date to be the same day at 00:00 UTC

server/metrics/global_status.go, server/services/v1/database/query_runner.go, server/services/v1/database/secondary_indexer.go, store/kv/measure.go
In the previous implementation, ignored secondary indexes were counted and non-ignored secondary indexes were double counted, because the count happened both in the kv layer and in query runner for updates. I removed the write counts from the kv layer.
Run the tests, tested it locally with ycsb data.
#918
=> fix: more accurate count of secondary indexes

go.mod, go.sum, lib/uuid/uuid.go, server/config/options.go, server/services/v1/billing/event.go, server/services/v1/billing/event_test.go, server/services/v1/billing/metronome.go, server/services/v1/billing/metronome_test.go, server/services/v1/billing/noop.go, server/services/v1/billing/provider.go, server/services/v1/management.go
- Metronome was being used with raw http requests, this change replaces it to use a openapi generated client.
- Interface to publish **usage** and **storage** events to Metronome, it is not hooked to any production workflow yet.
- Unit tests
TIG-1204
=> feat: APIs to push billing metrics to metronome

api/server/v1/tx.go, server/config/options.go, server/metadata/dictionary.go, server/metadata/tenant.go, server/request/request.go, server/request/request_test.go, server/services/v1/management.go, server/services/v1/namespace_metadata_provider.go
Allow cluster admins to delete namespace. This is required for internal clean up and this needs to be followed up with a restart of server for now as the memory state needs to be updated across all the nodes.
=> feat: Delete namespace implementation

query/filter/key_builder.go, query/filter/key_builder_test.go, schema/collection.go, schema/fields.go, server/services/v1/database/secondary_index_reader.go, server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, test/v1/server/secondary_index_test.go, value/secondary_value_order.go, value/value.go, value/value_test.go
Add a field type to each index field so that fields in an index will be ordered by type. The ordering follows the same order as BSON:
MinKey (internal type)
Null
Numbers (ints, longs, doubles, decimals)
Symbol, String
Object
Array
BinData
ObjectId
Boolean - false then true
Date
Timestamp
Regular Expression
MaxKey (internal type)
closes #976
=> feat: Order secondary indexes via field type

.github/workflows/test-docker-local-image.yaml, Makefile, server/metadata/tenant.go, server/metadata/tenant_test.go
* Fix panic on race condition when GetDatabaseBranches is called before Project is fully initialized in tenant.reload. (it only fixes the panic, doesn't fix underlying race)
* Add ability to build local docker image. It's useful to test local changes where multiple local instances need to be started.
=> Fix panic in GetDatabaseBranches

go.mod, go.sum, server/search/hits.go
In case the match is for the nested object, then it is part of "Highlight" so we need to bump up the client to have that. The matched response looks like this,
```
{
"result": {
"hits": [
{
"data": {
"object": {
"field": "foo"
},
"id": "3de5d938-83eb-40e6-9732-ddb05ebe9752",
"top_level_string": "foo"
},
"metadata": {
"created_at": "2023-04-07T00:42:27.144444Z",
"match": {
"fields": [
{
"name": "object.field"
},
{
"name": "top_level_string"
}
],
"score": "578730123365711994"
}
}
}
],
"facets": {},
"meta": {
"found": 127,
"total_pages": 127,
"page": {
"current": 1,
"size": 1
},
"matched_fields": [
"top_level_string",
"object.field"
]
},
"group": null
}
}
```
=> fix: Bump up search client with highlight object

schema/fields.go, schema/queryable_test.go
We convert date-time to int64 to support time-series filtering, but it won't be useful for the date-time array. This diff will simply convert date-time arrays to string arrays for storing in search.
=> fix: For array of date-time, convert it to string array for search instead of integer array

schema/collection.go, schema/collection_test.go, schema/rules.go, schema/search.go, server/search/hits.go, server/services/v1/common/converter.go, server/services/v1/common/converter_test.go, server/services/v1/database/mutator.go, server/services/v1/search/indexer.go, test/v1/server/search_test.go
For the search index user can have an `int64` field in the schema but can pass string values for these fields in the document during indexing. This will be converted to `int64` on the server side and stored as `int64`, meaning the value for this field will be returned as `int64` back to the user.
=> feat: Add support for automatically converting string to int64 based on schema

api/server/v1/tx.go, schema/collection.go, schema/fields.go, server/main.go, server/metadata/tenant.go, server/middleware/timeout.go, server/services/v1/api.go, server/services/v1/database/base_runner.go, server/services/v1/database/collection_runner.go, server/services/v1/database/indexer_runner.go, server/services/v1/database/query_runner_factory.go, server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, test/v1/server/document_test.go, test/v1/server/secondary_index_test.go
Adds an endpoint that will read all documents in a collection and add them to the secondary index. The bulk indexer will read in batches. If an error occurs it will try to decrease the number of documents read in a batch and try again.
All tests should pass. C
closes #1005
=> feat: bulk secondary index builder

server/config/options.go, server/services/v1/management.go
In the multi-region setup, not all cluster will need to expose management interface to create namespace. This PR allows users to configure cluster to disable namespace creation API.
=> feat: Allow disabling namespace creation at cluster level

internal/cache.go, internal/data.go, internal/data_test.go, server/services/v1/management.go, store/kv/kv_test.go
This makes encoding ~3 times faster.
Decoding is made O(1), so no special metadata-only decoding API is needed.
This is forward incompatible change.
=> Use proto for document metadata encoding

cmd/consistency/workload/document.go, query/filter/filter.go, schema/queryable.go, schema/search.go, test/v1/server/document_test.go
This allows if an array of objects is indexed, then filtering can be done inside it like this,
```
{"filter": {"arr.nested_field": "foo"}}
```
=> feat: Allow filtering for nested array of objects(one level) for standalone search index

server/search/hits.go, server/search/hits_test.go
We were returning only the parent name(array of objects) in case the search matches that field. This diff will return an exact nested field that matches in the case of an array of objects. The convention will be the same `parent.nested`
=> feat: Return matched token for nested fields in case of array of objects

cmd/admin/main.go, query/filter/comparison.go, query/filter/comparison_test.go, query/filter/filter.go, query/filter/filter_test.go, query/filter/key_builder.go, query/filter/like.go, query/filter/logical.go, query/filter/selector.go, test/v1/server/search_test.go, value/collation.go
Adding three more operands in the filters. 
- `$regex`: Provides regular expression capabilities for pattern-matching strings in queries.
- `$contains`: Contains reports whether the filter value is within the value stored in the field.
- `$not`: Not is the reverse of contains.
These operands can further filter database results or search index results. This is very useful for our hybrid search, where results are returned in the similarity order of vectors, and then using these operands, results can be narrowed.
Example Search Req:
```
{
"vector": {
"vec": [-0.12, -0.23, -0.56, -0.83]
},
"filter": {"StrValue": {"$contains": "hybrid"}}
}
```
=> feat: Support $regex, $contains, $not in filters(extending hybrid search functionality)

internal/data.go, server/services/v1/billing/metronome.go, server/services/v1/database/row_reader.go, test/v1/server/secondary_index_test.go
When a filter had a `_tigris_created_at` check and another field check the filtering would always fail because we did two separate checks on the filter. This adds the timestamps to the raw data and then does a single filtering check.
The current tests should pass
=> fix: Filtering with timestamp

query/filter/comparison.go, value/collation.go
Use empty collation if not set
=> fix: Use empty collation if not set

server/services/v1/api.go
The describe collection wasn't reacting to collection index changes because it was not checking the metadata has changed.
=> fix: check metadata before reading collection metadata

schema/queryable.go, server/metadata/tenant.go, server/metadata/tenant_tracker.go, server/quota/quota_test.go, server/quota/storage_test.go, server/services/v1/api.go, server/services/v1/realtime/device_session.go
One of the use cases of using the previous version of the search schema is to know if a field needs to be masked. This is only relevant for very old collections, so moving this logic to load all the schemas during startup only.
=> refactor: Optimize by loading schemas for search only during the start of the server

test/v1/server/realtime_test.go
Disabled realtime test for realtime  - fix and enable it back when we are ready for realtime. This is to improve CI health temporarily.
=> fix: Disabled realtime test

api/server/v1/marshaler.go, server/services/v1/api.go, server/services/v1/database/query_runner.go, server/services/v1/database/query_runner_factory.go, test/v1/server/document_test.go
Return the counts of documents in a collection. Optionally accept a filter to return the count of documents that matches the filter. 
```
curl '127.0.0.1:8081/v1/projects/p1/database/collections/foo/documents/count' -XPOST
{"count":2}
```
=> feat: Add count documents API

server/metrics/measurement.go, server/metrics/metronome.go, server/metrics/metronome_test.go, server/services/v1/billing/metronome.go, server/services/v1/billing/metronome_test.go
- restructuring metronome metrics for efficient querying
- fixing `recordTimerDuration` bug where tracing was not started before recording duration
- Unit tests
=> fix: `recordTimerDuration` not started for metronome metrics

query/filter/key_builder.go, query/filter/key_builder_test.go, test/v1/server/secondary_index_test.go
This fixes the case where the EQ key composer
would ignore a filter that contains a `eq` and a non-eq field
=> fix: EQ KeyBuilder ignoring EQ fields

Makefile
=> fix: do not error on rm if mocks dont exist

api/server/v1/search.go, go.mod, query/filter/key_builder.go, server/services/v1/billing/event_test.go, server/services/v1/billing/reporter.go, server/services/v1/billing/reporter_test.go, server/services/v1/database/secondary_index_reader.go, server/services/v1/search/base_runner.go, server/services/v1/search/errors.go, server/services/v1/search/indexer.go, server/services/v1/search/indexer_test.go, server/services/v1/search/runner.go, test/v1/server/search_test.go
For search indexes, when there is a batch index documents requests, instead of failing the entire batch, this diff will move individual document-related errors to the document level i.e. 
- If there is a missing id in a document (in case 'id' is explicitly set in the schema)
- In case of validation fails for the document
=> fix: For search index, move encoding/etc search errors on document level

server/metadata/namespace.go, server/services/v1/billing.go, server/services/v1/billing/metronome.go, server/services/v1/billing/reporter.go, server/services/v1/billing/reporter_test.go
- Some tenants have empty namespace ids in dev, they are being disabled from metronome permanently
- Metronome accounts would only be created if there is any usage, we will simply skip creating accounts for users that don't have any usage
- Unit tests
=> fix: Disable metronome permanently for invalid namespace ids

server/services/v1/billing/reporter.go
- `default_namespace` does not get persisted, hence disabling usage reporting for it
- Unit tests
=> fix: disable metronome reporting for default namespace

server/metrics/datadog.go, server/metrics/datadog_test.go
`db` was old metric tag used, tigris moved to project model (one project, one db) and the metric tags were updated to emit `project` along with `db` (for backward compatibility).
This PR removes the usage of old `db` tag in querying.
Updated tests.
=> fix: Switch to project metric tag while querying metrics

server/metadata/namespace.go, server/metadata/tenant.go, server/metadata/tenant_test.go, server/metrics/measurement.go, server/metrics/measurement_test.go, server/metrics/size.go, server/quota/storage.go
- Added methods `SearchIndexSize`, `ProjectSearchSize`,  `SearchSize` to metadata/tenant.go to get size of search tables. 
- Added respective unit test cases for the above methods
- Updating the search metrics while updating the mertics for namespace 
- Added the search index tags
make test command
#886
=> feat: search index metrics

schema/factory_builder.go, schema/fields.go, schema/fields_test.go, schema/rules.go, test/v1/server/collection_test.go
* This fixes external data validation using our schema.
* This would allow proper reconstruction of language schema.
* We would not need to cleanup nulls during import process. Just specify additional "null" as type.
=> Allow user to explicitly specify fields as nullable

server/services/v1/observability.go, server/services/v1/observability_test.go
Project and collection names were updated to allow `-` in the name. However the metric query endpoint did not allow it. This PR fixes this out of sync validation.
Updated existing test to cover this.
=> fix: Allow dashes in while querying metric tags

server/config/options.go, server/metrics/measurement.go, server/metrics/metronome.go, server/services/v1/billing.go, server/services/v1/billing/event.go, server/services/v1/billing/event_test.go, server/services/v1/billing/metronome.go, server/services/v1/billing/metronome_test.go, server/services/v1/billing/noop.go, server/services/v1/billing/provider.go, server/services/v1/billing/reporter_test.go, server/services/v1/billing_test.go
- Interface to request usage data from metronome within a time window:
```go
resp, err := metronome.GetUsage(ctx, cid, &UsageRequest{
BillableMetric: nil, // will get data for all metrics
StartTime:      &rt,
EndTime:        &rt,
NextPage:       &nextPageToken,
})
```
- Optionally, usage can be filtered by specific billing metric name like:
```go
resp, err := metronome.GetUsage(ctx, cid, &UsageRequest{
BillableMetric: &[]string{"search_units", "database_bytes"},
StartTime:      &startTime,
EndTime:        &endTime,
NextPage:       &nextPageToken,
})
```
- billing metric ids are hardcoded in config for now for dev/preview/prod, which will be loaded as an unbounded map
- Unit tests
=> feat: Request Usage data from metronome

api/server/v1/tx.go, cmd/consistency/workload/document.go, server/middleware/timeout.go, server/services/v1/api.go, server/services/v1/billing/metronome_test.go, server/services/v1/billing/provider.go, server/services/v1/database/base_runner.go, server/services/v1/database/collection_runner.go, server/services/v1/database/database_runner.go, server/services/v1/database/errors.go, server/services/v1/database/indexer_runner.go, server/services/v1/database/query_runner.go, server/services/v1/database/query_runner_factory.go, server/services/v1/database/request.go, server/services/v1/database/sessions.go, server/services/v1/database/stream_producer.go, test/v1/server/document_test.go
- Endpoint to build(backfill) collection search index
- Ensure sorting on field annotation is honored even if secondary indexes are enabled.
=> feat: Add support for building(backfilling) collection search index using an API

server/metadata/tenant.go
- There is an existing bug where `RefreshNamespaceAccounts()` is supposed to reload cached metadata from disk but it was not functional
- This change updates the in-memory cached namespace metadata after reload from disk
- Unit tests
=> fix: Saving metadata on refresh accounts to cache

server/services/v1/database/base_runner.go, server/services/v1/database/mutator.go, test/v1/server/document_test.go
In case of an update if there is a field with dot notation then we need to make sure to validate the schema with unflattened form.
=> fix: Fix schema validation for dot notation in Update Query

server/config/options.go, server/services/v1/database/base_runner.go, server/services/v1/database/search_indexer.go, server/services/v1/database/search_indexer_test.go, server/services/v1/search/indexer.go, test/v1/server/document_test.go, util/util.go, util/util_test.go
For an array of objects, if a field is set as null, then Search may return this extra field in a different form than stored. This diff is removing these extra fields that are not needed.
=> fix: Remove extra null fields from search response

server/services/v1/database/base_runner.go, test/v1/server/secondary_index_test.go
Fixes when the filter does not have an indexed field in the filter but the sort field is useable, the secondary secondary index can still be used
=> fix: Valid sort with no indexed fields in filter

server/services/v1/observability.go, server/services/v1/observability_test.go
While querying metrics across projects/collections/branches, they are passed as empty - allow server to make such requests.
Added unit test.
=> fix: Allow project/collection/branch name empty in query

api/server/v1/marshaler.go, config/server.dev.yaml, server/config/options.go, server/main.go, server/metadata/collection.go, server/metadata/collection_test.go, server/metadata/dictionary.go, server/metadata/dictionary_test.go, server/metadata/queue.go, server/metadata/queue_test.go, server/metadata/tenant.go, server/services/v1/database/indexer_runner.go, server/services/v1/database/secondary_index_measure.go, server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, server/services/v1/workers/worker.go, server/services/v1/workers/worker_test.go, test/docker/docker-compose.yml, test/v1/server/secondary_index_test.go
Adds background workers and a worker pool to build secondary indexes. The background workers are managed via the worker pool. The background workers are off by default. I would like to do another PR first with metrics to give deeper insight into the system before enabling. 
Current tests should pass 
This closes #780 #911 #913
=> feat: Background workers for index building

server/services/v1/billing/event.go, server/services/v1/billing/event_test.go, server/services/v1/billing/metronome.go
- Do not add any 0 value metrics to events being published to metronome
- When there are no metrics to publish, the whole event will be skipped
- Unit tests
=> fix: skip reporting 0 values to metronome

query/filter/selector.go, query/filter/selector_test.go, query/search/search_test.go, server/middleware/auth.go, server/services/v1/database/query_runner.go, test/v1/server/document_test.go, value/value.go
This diff removes any fallback logic and ensures that escaped characters and Unicode are handled properly during filtering.
Also details here about unmarshaler behavior with escaped characters: https://stackoverflow.com/questions/28595664/how-to-stop-json-marshal-from-escaping-and
=> fix: Handle filtering completely on Tigris layer for read queries, handle escaped characters and unicode properly

api/server/v1/header.go, server/metrics/measurement.go, server/middleware/headers.go, server/middleware/measure.go, server/middleware/middleware.go, store/kv/chunk.go
- Returning the server response time in headers. In the case of streaming, this will return the time taken just before sending the first byte i.e. TTFB.
- Fixing a bug in reverse iterator in case of chunking.
=> feat: Return server response time in headers

query/filter/key_builder_test.go, schema/collection.go, schema/fields.go, schema/queryable.go, schema/queryable_test.go, schema/schema.go, schema/schema_test.go, server/services/v1/database/base_runner.go, server/services/v1/database/collection_runner.go, server/services/v1/database/indexer_runner.go, server/services/v1/database/query_runner.go, server/services/v1/database/secondary_index_measure.go, server/services/v1/database/secondary_index_reader.go, server/services/v1/database/secondary_indexer.go, server/services/v1/database/secondary_indexer_test.go, server/services/v1/workers/worker.go
Configure secondary indexes to not index the timestamp metadata. Configure the secondary_indexer to only index indexes that are not in active mode. This is for the background worker to reduce the number of indexes being written to.
=> feat: Index metadata toggle and write mode index

server/config/options.go, server/metrics/measurement.go, server/middleware/headers.go, server/middleware/measure.go, server/middleware/middleware.go, server/services/v1/database/sessions.go
For write workloads, this will return database commit time and search index time separately in response headers.
=> feat: Add more server timing information in the header

schema/collection.go, schema/collection_test.go, server/services/v1/database/base_runner.go
Log request payload when schema validation fails
=> fix: Relax(allow nulls) schema validation for objects inside arrays

server/services/v1/database/query_runner.go
Long running insert and replace requests also have the number of documents logged.
Tested locally.
```
$ tigris insert --project=sampledb users \
> '[
>     {"id": 1, "name": "Jania McGrory", "balance": 6045.7},
>     {"id": 2, "name": "Bunny Instone", "balance": 2948.87}
> ]'
```
```
2023-05-15T14:20:31Z ERR metrics/measurement.go:442 long method call bytes received=130 bytes sent=45 grpc method=Insert has error=false result documents=2 start time=1684160431 stop time=1684160431 tenant name=default_namespace_default_namespace threshold=1 total time (ms)=25
```
TIG-1509
=> feat: long request contains number of inserted documents

server/services/v1/search.go, server/services/v1/search/session.go
GetIndexes are read-only, so we don't need to update the metadata version.
=> fix: Do not increment version on get index requests

server/middleware/authz.go
Fixed the error reset for log_only with named return parameter.
=> fix: Fixed the error reset for log_only

server/metadata/namespace.go, server/metadata/tenant.go, server/services/v1/billing/reporter.go, server/services/v1/billing/reporter_test.go
- Made accounts on namespace object to be of pointer type so they are not copied/overridden
- Fixed the existing unit tests to reflect the change
- Unit tests
=> fix: avoid saving copies for namespace accounts

config/server.dev.yaml, config/server.test.yaml, server/config/options.go, server/metadata/key_generator.go, server/metadata/metadata.go, server/services/v1/billing_test.go, server/services/v1/database/search_reader.go, server/services/v1/search/base_runner.go, server/services/v1/search/runner.go, server/services/v1/search/session.go, store/kv/compression.go
- Count single write for search deletes
- Make minimum threshold for compression configurable
- Fixing go imports
=> fix: Count single write unit for each search deletes, minimum threshold for compression configurable, and fixing go imports

query/filter/key_builder.go, server/services/v1/database/base_runner.go, server/services/v1/database/query_runner.go
Adding an error log when keys generated are empty but no errors are returned by the API.
=> chore: Add a log when builder not returning an error and keys are empty

api/server/v1/tx.go, query/filter/key_builder.go, schema/fields.go, schema/fields_test.go, schema/inference.go, schema/inference_test.go, schema/lang/go_test.go, schema/lang/java.go, schema/lang/java_test.go, schema/lang/multi_type.go, schema/lang/schema.go, schema/lang/schema_test.go, schema/lang/typescript.go, schema/lang/typescript_test.go, server/config/options.go, server/metadata/tenant.go, server/services/v1/billing/reporter.go, server/services/v1/billing/reporter_test.go, templates/schema/go/object.gotmpl, test/config/config.go, test/v1/server/auth_test.go
if JSON schema type is nullable, for example:
```
SomeField: { "type" : ["integer", "null"] }
```
it is generated as:
```
SomeField *int
```
in the Golang model.
=> Properly generate pointer types in language schema

server/metadata/tenant.go, server/services/v1/search/session.go
No need to bump up the metadata version if the index schema is the same.
=> refactor: Do not increment metadata version if no changes in index schema

server/config/options.go, server/metrics/measurement.go, server/metrics/metrics.go, server/metrics/metronome.go, server/metrics/metronome_test.go, server/services/v1/billing/metronome.go, server/services/v1/billing/metronome_test.go
Refactor metronome metrics to be in-line with the rest and make sure tags won't be different in the same scope.
Right now the new metrics are additional to the old, one, needs to be deleted.
Check the metronome alerts in dev.
TIG-1549
=> refactor: refactor metronome metrics with consistent tags

server/config/options.go, server/services/v1/billing/provider.go, server/services/v1/billing/provider_test.go, server/services/v1/billing/reporter.go
- Removes `enabled` key from billing config
- And introduces `disabled` key, which by default is false. Existing dev/preview/prod deployments should continue to operate as usual because this key will be false by default.
- this will eliminate a few keys from config while still retaining control
- Any new environments would have usage reporting turned on by default
- Unit tests
=> fix: enabling metronome and usage reporting by default

server/config/options.go, server/metadata/tenant.go
Temporarily to resolve bigger tenant reloading. Skip certain search indices.
Test on dev.
=> fix: Skip reloading certain search indices

server/metadata/tenant.go
=> Release Beta

api/server/v1/validator.go, server/metadata/namespace.go, server/metadata/tenant.go, server/services/v1/api.go, server/services/v1/database/database_runner.go
- Create Project request can include optional metadata:
```shell
$ ➔  echo -n '{"options": {"limits": {"max_search_indexes": 3}}}' | http POST localhost:8081/v1/projects/catalog/create                                      
HTTP/1.1 200 OK
Content-Length: 61
Content-Type: application/json
Date: Tue, 13 Jun 2023 21:24:38 GMT
Server-Timing: total;dur=18,commit;dur=6
Vary: Origin
{
"message": "project created successfully",
"status": "created"
}
```
- List projects to include project metadata if exists:
```shell
$ ➔  http GET localhost:8081/v1/projects
HTTP/1.1 200 OK
Content-Length: 124
Content-Type: application/json
Date: Tue, 13 Jun 2023 21:24:41 GMT
Server-Timing: total;dur=13
Vary: Origin
{
"projects": [
{
"limits": {
"max_search_indexes": 3
},
"project": "catalog"
},
{
"limits": { …
```
=> feat: Persist project limits in project metadata

Makefile, api/server/v1/marshaler.go, server/config/options.go, server/metadata/tenant.go, server/services/v1/api.go, server/services/v1/database/collection_runner.go, server/services/v1/database/database_runner.go, server/services/v1/search/runner.go
- Ability to update project metadata
- Create index and Create collections now include an added check for quota if it is set.
=> feat: Collection and Index creation to respect specified limits

schema/search.go, server/config/options.go, server/metadata/tenant.go
```shell
$ -> http PUT localhost:8081/v1/search/indexes/shoes
{
schema: {
title: 'shoes_index',
properties: {
name: {
type: 'string',
},
},
options: {
token_separators: [ '-' ],
},
}           
```
```shell
$ ➔  http GET localhost:8081/v1/projects/todo_app/search/indexes                                                                                                 ±[●][tokenize]
HTTP/1.1 200 OK
Content-Length: 169
Content-Type: application/json
Date: Wed, 21 Jun 2023 23:42:48 GMT
Server-Timing: total;dur=2
Vary: Origin
{
"indexes": [
{
"name": "shoes",
"schema": {
"options": {
"token_separators": [
"-"
]
},
"properties": {
"name": {
"type": "string"
}
},
"source": {
"type": "external"
},
"title": "shoes_index"
}
}
]
}
```
```shell
$ ➔  http GET localhost:8108/collections …
```
=> feat: Adding custom token separators to search index
