tigrisdata/tigris

api/server/v1/validator.go
test/v1/server/collection_test.go

Includes transactional context in collections API

Upgrade API to v1.0.0-alpha.2

---

schema/collection.go
schema/schema.go
server/metadata/encoding/dictionary.go
server/metadata/encoding/dictionary_test.go
server/metadata/encoding/schema.go
server/metadata/encoding/schema_test.go
server/metadata/tenant.go
server/metadata/tenant_test.go

To support default or custom namespace. Have a database class to manage multiple collections.
Once we land this, the next part is to integrate this with the API layer.

feat: tenant class to manage the namespaces, databases and collections

---

server/metadata/encoding/dictionary.go
server/metadata/encoding/dictionary_test.go
server/metadata/encoding/schema.go
server/metadata/encoding/schema_test.go
server/metadata/tenant.go
server/metadata/tenant_test.go

This will be used by the server layer to support drop database, drop collection APIs.

feat: add drop functionality for database, collections and indexes in the tenant class.

---

encoding/encoding.go
keys/key.go
query/filter/key_builder.go
query/filter/key_builder_test.go
server/metadata/encoding/dictionary.go
server/metadata/encoding/dictionary_test.go
server/metadata/encoding/schema.go
server/metadata/key_encoder.go
server/metadata/key_encoder_test.go
server/metadata/meta_version.go
server/metadata/meta_version_test.go
server/services/v1/query_runner.go
server/transaction/session.go
store/kv/fdb.go
store/kv/kv.go
store/kv/kv_test.go

Key encoder will be used by the api layer to encode keys using dictionary encoded values of ns, db, and collection.

feat: implement key encoder

---

README.md

Fixes tigrisdb-cli example in README

Client invocation fix

---

server/services/v1/query_runner.go
test/v1/server/document_test.go

https://github.com/tigrisdata/tigrisdb/issues/208

fix: use NotFound instead of InvalidArgument error code if database/collection doesn't exist

---

schema/collection.go
schema/collection_test.go
test/v1/server/collection_test.go
test/v1/server/document_test.go

https://github.com/tigrisdata/tigrisdb/issues/210

feat: disallow additional properties by default to do strict schema validation

---

api/server/v1/marshaler.go
server/services/v1/api.go
server/services/v1/query_runner.go
test/v1/server/collection_test.go
test/v1/server/database_test.go

https://github.com/tigrisdata/tigrisdb-api/pull/25

fix!: Synced API changes

---

api/server/v1/marshaler.go
api/server/v1/validator.go
internal/data.go
internal/data.proto
schema/collection.go
server/services/v1/api.go
server/services/v1/query_runner.go
server/services/v1/request.go
test/v1/server/collection_test.go
test/v1/server/database_test.go

feat: Describe database and collection API implementation

---

cmd/consistency/consistency.go
go.mod
go.sum
server/metadata/encoding/dictionary_test.go
server/metadata/meta_version_test.go
server/metadata/tenant_test.go
server/midddleware/auth_test.go
store/kv/fdb.go
store/kv/kv_test.go
test/v1/client/client_test.go
test/v1/client/driver_test.go
test/v1/server/collection_test.go
test/v1/server/database_test.go
test/v1/server/document_test.go
test/v1/server/integration_test.go
util/log/log.go

* Fix transaction rollback on failure
* Automatically retry implicit transactions
* Update client to newest and add high level client integration tests
* Removing logging from -v output
* Fix FDB connection when test on the hosts and server in the docker
* Various clean ups

Test cleanup

---

api/server/v1/marshaler.go
go.mod
go.sum
server/services/v1/api.go
server/services/v1/query_runner.go
server/services/v1/request.go
test/v1/client/client_test.go
test/v1/server/document_test.go

Marshal response metadata timestamp as RFC3339Nano

Proper marshal response metadata timestamps

---

server/grpc/grpc.go

https://github.com/grpc/grpc/blob/master/doc/server-reflection.md

feat: Added Reflection service to gRPC server

---

.gitignore

Ignores Visual Studio Code folder data.

chore: Add .vscode to gitignore

---

.github/workflows/push-docker-image.yaml

Modifies the CI process to build and publish ARM64 images also.

chore: build and publish arm64 images also

---

server/muxer/muxer.go
store/search/search.go

Trivial change. Adds a few more informational logs that may help with triaging deployment issues.

feat: add more logging around startup

---

Makefile
README.md
config/server.dev.yaml
go.mod
go.sum
server/config/config.go
store/kv/fdb.go
store/search/search.go

* Upgrade FDB Go bindings to 7.1
* Update README with instructions for server debugging
* Added local_run target to bring the server up on the host for debugging in IDE
* Upgrade Go client to v1.0.0-alpha.18

Upgrade FDB API to 7.1

---

deployment/manifests/base/server.yaml

Add typesense test key to deployment.

fix: add ts test key to deployment

---

docker/Dockerfile
server/config/config.go
server/config/options.go
server/main.go
server/metadata/tenant.go
server/metadata/tenant_test.go
server/midddleware/auth.go
server/midddleware/auth_test.go
server/midddleware/middleware.go
server/midddleware/namespace.go
server/midddleware/request_metadata.go
server/midddleware/request_metadata_test.go
server/muxer/grpc.go
server/muxer/http.go
server/muxer/muxer.go
server/services/v1/admin.go
server/services/v1/sessions.go
server/types/types.go

feat: Add namespace based authz

---

server/midddleware/metrics_test.go

Use a more realistic namespace creation in test.

fix: more realistic namespace creation in test

---

deployment/manifests/base/server.yaml
util/log/log.go

Small tweak to ensure that by default deployments will use a reasonable sample rate. Also tweaks configuration to have symmetrical keys.

feat: set sample rate in default deployment

---

server/config/options.go
server/midddleware/auth.go
server/midddleware/auth_test.go

- snake case for auth config for consistency
- admin namespaces turned into []string from Map (HashSet)

refactor: snake case config and hashset --> string[] for adminNamespaces

---

server/config/options.go
server/metrics/fdb.go
server/metrics/metrics.go
server/metrics/search.go
server/metrics/search_test.go
server/metrics/tenant.go
store/search/search.go
store/search/ts.go

Implements metrics for search.

feat: implement search metrics

---

api/server/v1/marshaler.go
api/server/v1/marshaler_test.go
api/server/v1/validator.go
query/read/fields.go
query/search/search.go
server/services/v1/query_runner.go
server/services/v1/query_runner_test.go
server/services/v1/search_reader.go

- Implementation for `include_fields` and `exclude_fields` on search api

feat: read fields support for search

---

go.mod
go.sum
server/services/v1/api.go
test/v1/client/driver_test.go

Delete events were not emitted

---

server/metrics/tracing.go
server/midddleware/tracing.go

Make service names consistent.

fix: get service names consistent

---

server/metrics/tracing.go
server/middleware/tracing.go
store/kv/kv.go
store/search/ts.go

Traces will catch errors, they will have the error codes and the stack traces with them.

feat: traces catching errors

---

Makefile
config/server.dev.yaml
test/docker/docker-compose.yml
test/v1/server/collection_test.go
test/v1/server/document_test.go
test/v1/server/integration_test.go

* Allow to run/debug individual tests in IDE
* Fix local_run target. Now FDB on the host should not be needed.
* Fix exit code of `make test`

Improve integrations tests

---

server/metrics/fdb.go
server/metrics/fdb_test.go
server/metrics/metrics.go
server/metrics/requests.go
server/metrics/requests_test.go
server/metrics/session.go
server/metrics/session_test.go
server/metrics/tracing.go
server/middleware/tracing.go
server/services/v1/api.go
server/services/v1/sessions.go
server/transaction/manager.go
store/kv/kv.go
store/search/ts.go

Instrumentation for session manager (both tracing and metrics)

feat: instrumentation for session

---

api/server/v1/marshaler.go
server/services/v1/auth.go

Fixed oauth/token endpoint to accept application/x-www-form-urlencoded payload

fix: Fixed oauth/token endpoint to accept x-www-form-urlencoded

---

server/metrics/tags.go
server/metrics/tracing.go

* Removed dead constant from txmanager monitoring
* Determining error type are now in separate helper functions

refactor: specific error handlers in separate functions

---

server/config/options.go
server/quota/quota.go
server/quota/quota_test.go

* Report size metrics peridocally
* Moved

feat: Report size metrics periodically

---

api/server/v1/marshaler.go

Fixed the QueryTimeSeriesMetricsRequest marshaler to work with enum for HTTP/json

fix: Fixed the QueryTimeSeriesMetricsRequest marshaler

---

server/quota/quota.go

Report sizes with disabled quotas.

fix: report size with disabled quotas

---

server/metrics/fdb.go
server/metrics/fdb_test.go
server/metrics/metrics.go
server/metrics/network.go
server/metrics/requests.go
server/metrics/search.go
server/metrics/search_test.go
server/metrics/session.go
server/metrics/session_test.go
server/metrics/tracing_test.go
server/middleware/tracing.go
server/services/v1/sessions.go
store/kv/kv.go
store/search/ts.go

Move to timers instead of histograms.

fix: move histograms to timers

---

api/openapi.yaml
server/config/options.go
server/metadata/tenant.go
server/quota/quota.go

All size metrics for all tenants updates every 5 minutes regardless of the namespace of the request it hits (the amount of time is configurable).

feat: size metrics updated periodically

---

api/server/v1/error.go
api/server/v1/marshaler.go
go.mod
go.sum
lib/date/converter.go
lib/date/converter_test.go
server/config/options.go
server/middleware/auth.go
server/request/request.go
server/services/v1/auth.go
server/services/v1/observability.go

- Tigris users will be able to create their applications. 
- Each application will have credentials generated.
- Users then can supply these application credentials to their software application for authentication and authorization while calling Tigris API.

feat: Added APIs for app based authentication/authorization

---

server/metrics/tenant.go
server/middleware/auth.go

Only log error of not finding namespace if the namespace isolation is enabled

chore: Refactored to reduce log flooding

---

store/search/ts.go

chore: remove extra counter

---

server/services/v1/search_reader.go

Temporary workaround to return at least one facet, will be refactored later

fix: Return atleast one facet

---

server/middleware/auth.go

Remove tracing from authentication measurements.

chore: remove tracing from auth measurement

---

server/middleware/auth.go

Fix possible panic when authentication is enabled.

fix: fix authentication metrics

---

server/services/v1/key_generator.go

Only needed, If we need to append auto-generated keys to the input document.

fix: Mutate the copy of the input document

---

api/server/v1/marshaler.go
api/server/v1/validator.go
server/config/options.go
server/metadata/tenant.go
server/metadata/users.go
server/middleware/auth.go
server/middleware/auth_test.go
server/middleware/middleware.go
server/middleware/namespace.go
server/request/request.go
server/services/v1/auth.go
server/services/v1/auth_provider.go
server/services/v1/service.go
server/services/v1/user.go
server/services/v1/user_metadata_provider.go

Alpha release

---

deployment/manifests/base/deployment.yaml
go.mod
go.sum
server/services/v1/admin.go
server/services/v1/auth.go
server/services/v1/observability.go
server/services/v1/user.go
server/services/v1/version.go
test/v1/server/admin_test.go
test/v1/server/database_test.go
test/v1/server/document_test.go
test/v1/server/integration_test.go
test/v1/server/server_test.go

* OpenAPI in single file
* Paths changed from `/*/v1/`, to `/v1/*`
BREAKING CHANGE: HTTP paths has changed from /api/v1/* to /v1/*

fix: Refactored API

---

server/metrics/query.go
server/metrics/query_test.go
server/metrics/requests.go
server/services/v1/api.go
server/services/v1/query_runner.go

Initial take on query runner based tags.

feat: query level metrics (tags based on how were they executed)

---

README.md

Fix: Update the broken links

---

Makefile
test/docker/docker-compose.yml
test/docker/grafana/add_victoriametrics_datasource.sh
test/docker/victoriametrics/vmagent.yml

Change prometheus to victoriametrics in local setup.

feat: change grafana to victoriametrics in local setup

---

server/metrics/measurement.go

An invalid tracing error was displayed when tracing was turned off, but metrics was turned on.
```
2022-10-10T05:56:08Z ERR metrics/measurement.go:296 recordTimerDuration was called on a span that was not started ot stopped resource_name=/tigrisdata.v1.Tigris/CreateDatabase service_name=tigris-server
```
The measurement type is used both by tracing and metrics. So the logic needs to happen even if tracing is turned off.
Added some more debug messages for easier troubleshooting of future issues like this.

fix: invalid display of tracing error

---

server/quota/namespace.go
server/quota/namespace_test.go
server/request/request.go
server/request/request_test.go
server/services/v1/query_runner.go

* Fix inital non-default namespace limits

Allow human user go 5% beyond quota limit

---

server/quota/namespace.go
server/quota/namespace_test.go
server/request/request.go
server/request/request_test.go
server/services/v1/query_runner.go

* Fix inital non-default namespace limits

Beta release

---

server/main.go
server/metrics/fdb_test.go
server/metrics/measurement.go
server/metrics/measurement_test.go
server/metrics/metrics.go
server/metrics/metrics_test.go
server/metrics/network.go
server/metrics/network_test.go
server/metrics/quota_test.go
server/metrics/requests_test.go
server/metrics/search_test.go
server/metrics/session_test.go
server/metrics/size.go
server/metrics/size_test.go
server/middleware/measure.go
server/quota/namespace.go
server/services/v1/api.go

* Disable tracing when only metrics enabled
* Some refactoring

Fix crash with metrics disabled

---

server/metrics/measurement.go

A possible memory could happen when a child span finishes with errors, and we lose the parent span from the context, so it can't be closed properly. We need to track parents similarly to when the span finishes ok.

fix: fix memory leak of measurements finished with errors

---

server/metadata/dictionary.go
server/metadata/dictionary_test.go
server/metadata/key_encoder_test.go
server/metadata/tenant.go
server/metadata/tenant_test.go
server/quota/namespace_test.go
server/quota/quota_test.go
server/quota/storage_test.go
server/services/v1/management.go
test/v1/server/management_test.go

Enhanced namespace from string:uint32 pair to structured object.

feat: Enhancements to namespace

---

api/server/v1/tx.go
server/middleware/auth.go
server/middleware/namespace.go
server/request/request.go
server/services/v1/conversion.go
server/services/v1/management.go
server/services/v1/user_metadata_provider.go
test/v1/server/management_test.go

- Fixed auth for newer namespace creation.
- Fixed a flaky test.

fix: Fixed the auth for newer namespace creation

---

Makefile
test/docker/docker-compose.yml

chore: have jaeger in make run_full

---

server/config/options.go

chore: add p99 back

---

api/server/v1/marshaler.go
server/services/v1/management.go
server/services/v1/namespace_metadata_provider.go
server/services/v1/service.go
server/services/v1/user_metadata_provider.go

Tests will be added in the form of cli_test

feat: Implemented namespace metadata API

---

server/services/v1/auth_provider.go

- Enables platform to associate project <> applications.

feat: Associate apps to projects

---

server/metadata/database.go
server/metadata/namespaces.go
server/metadata/namespaces_test.go
server/metadata/tenant.go
server/metadata/tenant_test.go
server/middleware/auth.go
server/quota/quota_test.go
server/quota/storage_test.go
server/request/request.go
server/request/request_test.go
server/services/v1/api.go
server/services/v1/auth_provider.go
server/services/v1/query_runner.go
server/services/v1/service.go

Start to manage metadata for the database/project.

feat: Maintain database metadata

---

server/metrics/tags.go
server/metrics/tags_test.go
server/middleware/measure.go
server/middleware/metadata_extractor.go
server/request/request.go

Enriched request metadata with the intention to use it later for app<>project and role base access control.

feat: Added db/collection as part of request metadata

---

server/metrics/requests.go
server/middleware/measure.go
server/request/request.go
server/request/request_test.go

metrics will contain the user `sub` tag.

feat: Tag user sub for metrics

---

server/middleware/measure.go

fix: no tracing inside streamed request

---

reviewpad.yml

Onboarding Reviewpad into the tigris.

feat: add reviewpad.yml

---

server/middleware/measure.go
server/services/v1/api.go
server/services/v1/management.go
server/services/v1/service.go
test/v1/server/management_test.go

This PR moves the apps related api from management to the main api under the scope of the project.

refactor!: Moved apps api under project

---

server/services/v1/api.go
server/services/v1/auth/auth0.go
server/services/v1/auth/noop.go
server/services/v1/auth/provider.go
test/v1/server/management_test.go

- The application APIs path is changed from application to apps/keys [updating all the APIs for that]
- Pulling in the latest API changes as we have moved List APIs from post to get.

fix! : Update application path to appKeys

---

test/v1/cli/backup.sh
test/v1/cli/import.sh
test/v1/cli/scaffold.sh
test/v1/cli/tests.sh

Sync tests from CLI repo after projects (aka breaking change) release.

Fix CLI tests

---

server/services/v1/database/sessions.go

Fix post commit error message

---

api/server/v1/realtime.go
server/main.go
server/metadata/key_encoder.go
server/metadata/tenant.go
server/services/v1/realtime/factory.go
server/services/v1/realtime/factory_test.go
server/services/v1/realtime/sessions.go
test/config/config.go
test/docker/docker-compose.yml
test/v1/server/integration_test.go
test/v1/server/realtime_test.go

Integration test for HTTP realtime APIs

feat: Basic integration tests for realtime HTTP APIs

---

cmd/realtime/app/app.go
cmd/realtime/app/device.go
cmd/realtime/main.go
server/services/v1/realtime/device_session.go
server/services/v1/realtime/serialization.go

A small cmd-line app to test real-time WS functionality.

feat: Realtime WS testing app

---

reviewpad.yml

* Fail release PR with no fix or feature commits
* Automatically merge release PR once approved

Protect release PRs

---

schema/fields.go
test/v1/server/document_test.go

* Retain title property in the nested objects

Test required fields validation

---

Makefile
server/services/v1/realtime.go
server/services/v1/realtime/channel_test.go
server/services/v1/realtime/device_session.go
server/services/v1/realtime/serialization.go
test/docker/docker-compose.yml

This is ongoing work on the Realtime functionality. This adds support to encode and decode messages that are encoded with msgpack.  We also didn't correctly handle attach/detach messages. This has been fixed.

feat: Add msgpack support to Realtime

---

api/server/v1/cache.go
go.mod
server/metadata/database.go
server/metadata/key_encoder.go
server/metadata/key_encoder_test.go
server/metadata/namespaces.go
server/metadata/namespaces_test.go
server/metadata/tenant.go
server/request/request.go
server/services/v1/api.go
server/services/v1/cache.go
server/services/v1/cache/request.go
server/services/v1/cache/runner.go
server/services/v1/cache/sessions.go
server/services/v1/database/query_runner.go
server/services/v1/database/request.go
server/services/v1/service.go
store/cache/errors.go
test/docker/docker-compose.yml
test/v1/server/cache_test.go

feat: Implemented cache API

---

server/metadata/tenant.go
server/services/v1/cache.go
server/services/v1/cache/request.go
server/services/v1/cache/runner.go
test/v1/server/cache_test.go

feat: Implemented ListCaches API

---

.golangci.yaml
api/server/v1/cache.go
api/server/v1/marshaler.go
cmd/consistency/workload/workload_ddl.go
query/filter/key_builder.go
schema/inference.go
schema/inference_test.go
schema/lang/java_test.go
schema/lang/typescript_test.go
schema/schema.go
server/config/config.go
server/metadata/tenant.go
server/metrics/datadog.go
server/quota/namespace_test.go
server/quota/node_test.go
server/quota/quota_test.go
server/quota/storage_test.go
server/request/request.go
server/request/request_test.go
server/services/v1/database/query_runner.go
server/services/v1/database/sessions.go
server/transaction/manager.go
test/v1/server/management_test.go

* Fixed loosing errors
* Fixed naked returns in big functions
* Removed erroneous golint from //nolint annotations

Fix errors caught by lints

---

schema/collection.go
server/metadata/tenant.go
server/services/v1/database/query_runner.go
test/v1/server/document_test.go

* Encode the name during collection creation only
* Combine getDatabse and getCollection
* Generalize get iterator code for update and delete
No functional change. Should be covered by existing tests.

Don't encode collection name on every request

---

api/server/v1/cache.go
server/services/v1/cache.go
server/services/v1/cache/request.go
server/services/v1/cache/runner.go
server/services/v1/realtime/heartbeat.go
store/cache/cache.go
store/cache/store.go
test/v1/server/cache_test.go

- Added support for `PX` options for Set operation. 
- Added GetSet operation.
- Integration test added.

fix: GetSet implementation and Px options for Set cache operation

---

api/server/v1/validator.go
schema/fields.go
schema/fields_test.go
test/v1/server/collection_test.go
test/v1/server/database_test.go
util/util.go

Field-level restrictions are very verbose, removing them.

fix: Remove language keywords restrictions

---

schema/collection.go
schema/schema.go
schema/schema_test.go
server/services/v1/database/query_runner.go

Cleaning up topic-type references in the code.

refactor: cleanup topic type from collection at multiple places

---

query/update/operator.go
query/update/operator_test.go
server/services/v1/database/query_runner.go
server/services/v1/realtime/pusher.go
server/services/v1/realtime/serialization.go
test/v1/server/document_test.go

Release Beta

---

.github/workflows/release.yaml

Upgrade Node version
Trigger a release

Fix Node version in release workflow

---

docker/service-local.sh

Fix local-image service-start script

---

.github/workflows/test-docker-local-image.yaml
docker/service-local.sh
test/v1/cli/tests.sh

Add local docker image test workflow
This change is the test.

Test local image

---

api/server/v1/search.go
schema/search.go
server/config/config.go
server/metadata/database.go
server/metadata/errors.go
server/metadata/schema.go
server/metadata/subscope_registry.go
server/metadata/tenant.go
server/metadata/tenant_test.go
server/services/v1/cache/runner.go
server/services/v1/search.go
server/services/v1/search/errors.go
server/services/v1/search/response.go
server/services/v1/search/runner.go
server/services/v1/search/session.go
server/services/v1/service.go
store/cache/errors.go

A service to manage search functionality. This service has the following functionality implemented as part of this diff,
- Create Or Update Search Index
- Delete Search Index
- List Search Indexes

feat: Search service and implementation of index management APIs

---

query/update/operator.go

docs: docstring for atomic update api

---

README.md

Fixed broken links from README
N/A

docs: Fixed README broken links

---

README.md

Fixing the links in the README that are broken after docs restructuring.

Fix more links in README

---

api/server/v1/search.go
api/server/v1/validator.go
lib/json/encoder.go
schema/search.go
server/metadata/errors.go
server/metadata/tenant.go
server/muxer/http.go
server/services/v1/database/search_indexer.go
server/services/v1/database/sessions.go
server/services/v1/search.go
server/services/v1/search/errors.go
server/services/v1/search/indexer.go
server/services/v1/search/runner.go
server/services/v1/search/session.go
server/services/v1/service.go
store/search/errors.go
store/search/search.go
store/search/ts.go
test/v1/client/driver_test.go
test/v1/server/integration_test.go
test/v1/server/search_test.go

This diff implementing the following search APIs
- Creating document by Id
- Creating multiple documents
- Creating or replacing multiple documents
- Updating multiple documents
- Deleting multiple documents
- Reading multiple documents

feat: Search crud APIs

---

docs/rfcs/001-secondary-indexes.md

This is the RFC for secondary indexes in Tigris

docs: Add RFC for secondary indexes

---

README.md

fix: Add discord community

---

query/filter/filter.go
query/filter/selector.go
server/services/v1/database/query_runner.go
value/collation.go
value/value.go
value/value_test.go

Uses text/collate to compare strings. This will create a more consistent string comparison. Currently only supports english and we can expand it later to support more languages.
This is a small PR to assist with some of the secondary index work

feat: Create collation wrapper for value

---

schema/search.go
server/services/v1/search/runner.go

A filter is added to restrict the result set.

feat: Support for filtering list indexes response

---

server/metadata/cluster.go
server/metadata/cluster_test.go
server/metadata/collection.go
server/metadata/collection_test.go
server/metadata/dictionary.go
server/metadata/dictionary_test.go
server/metadata/metadata.go
server/metadata/namespaces.go
server/metadata/namespaces_test.go
server/metadata/schema.go
server/metadata/schema_test.go
server/metadata/subscope_registry.go
server/metadata/tenant.go
server/metadata/users.go
server/metadata/users_test.go
server/services/v1/service.go

* Generalized metadata subspaces CRUDs
* Generalized main and search schema CRUDs

 Added cluster and collection metadata subspaces

---

api/server/v1/search.go
server/metadata/tenant.go
server/services/v1/search.go
server/services/v1/search/runner.go
store/search/ts.go

Adding a get index api to return information about search index.

feat: Get Index API

---

server/middleware/auth.go

Updating the custom claim schema in JWT from
```
"https://tigris/u": {
"email": "<>"
},
"https://tigris/n": {
"code": "<>"
},
```
to
```
"https://tigris": {
"nc": "<>",
"ue": "<>"
},
```
And supports both while we migrate.
Tested this manually. We lack the testing base work around this currently. This will be covered in future.

refactor: Updated schema of custom claims in JWT

---

server/metadata/key_encoder_test.go
server/metadata/tenant.go
server/services/v1/database/search_indexer.go

- GetCollection was failing for database branches, and documents were not being indexed
- This should fix Search on database branches
- Unit tests
TIG-1032

fix: move getCollection from tenant to db

---

README.md

Updated the tagline and add trailing slash to the links

Update tag line and fix links

---

api/server/v1/search.go
schema/search.go
server/metadata/dictionary.go
server/services/v1/search.go
server/services/v1/search/indexer.go
server/services/v1/search/reader.go
server/services/v1/search/response.go
server/services/v1/search/runner.go
test/v1/server/search_test.go

Adding the search API for search indexes. 
Todo: there is some redundancy in the reader/search logic that we have here and similar already exists in the database package. Need to consolidate it in further diffs.

feat: Add search API for search product

---

.github/workflows/cli-test.yaml
.github/workflows/go-test.yaml
Makefile
api/server/v1/marshaler.go
docker/Dockerfile
server/main.go
store/kv/base.go
store/kv/fdb.go
test/docker/docker-compose.yml
test/v1/client/client_test.go
util/log/log.go
util/util.go

Gather integration tests coverage

---

.github/workflows/cli-test.yaml
.github/workflows/go-test.yaml

Explicitly enable main branch in tests to publish coverage

---

api/server/v1/marshaler.go
server/services/v1/api.go
server/services/v1/database/database_runner.go

- `GET /database/branches` api to return database branch names and relevant metadata
Closes #820

feat: GET /branches to return list of database branches

---

server/services/v1/database/query_runner.go
test/v1/server/document_test.go

Honor skip option for the read queries

fix: Honor skip option for the read queries

---

api/server/v1/search.go

Proper unmarshal search index request

---

server/metadata/namespace.go
test/docker/docker-compose.yml

Need to bring tigris_realtime container to test from the host.

chore: Fix make local_test

---

schema/fields.go
schema/fields_test.go
store/search/ts.go
test/v1/server/document_test.go

feat: Allow more fields attributes

---

server/services/v1/namespace_metadata_provider.go
server/services/v1/user_metadata_provider.go

Return empty response on non-existent user metadata

---

test/v1/client/client_test.go

Fixes this test often failing locally because it doesn't clean up after

chore: make client test re-runnable

---

server/metrics/metrics.go

Enable quota metrics by default

---

server/services/v1/search/runner.go
test/v1/server/search_test.go

Fix crash on non string id in the document

---

api/server/v1/marshaler.go
api/server/v1/marshaler_test.go
api/server/v1/search.go
server/services/v1/search/runner.go
test/v1/server/search_test.go

- Unifying internal response fields for index search

fix: Unify search index/collection internal response fields

---

schema/fields.go
schema/search.go
schema/search_test.go
server/services/v1/search/runner.go

Add more validations for search schema

fix: Add more validations for search schema

---

api/server/v1/header.go
query/filter/selector.go
server/request/request.go
server/services/v1/database/base_runner.go
server/services/v1/database/query_runner.go
test/v1/server/schema_test.go

Skip schema validation on write if `Tigris-Schema-Sign-Off : true` header is set.

Optionally disable schema validation

---

schema/factory_builder.go
schema/schema_test.go
test/v1/server/collection_test.go
test/v1/server/search_test.go

Covering all the cases through integration tests for field attributes

chore: Adding more integration tests for field attributes

---

server/services/v1/api.go

Expose number of deleted rows in delete API

Return deleted count

---

server/config/options.go
server/quota/namespace_test.go
server/quota/node_test.go

Equalize read and write unit size

---

server/services/v1/auth/gotrue.go
server/services/v1/auth/gotrue_test.go

Added test to inspect id/secret's characters. This is to extend https://github.com/tigrisdata/tigris/pull/937

chore: Inspect generated id and secret's characters

---

api/server/v1/header.go
go.mod
go.sum
server/config/options.go
server/middleware/auth.go
server/middleware/auth_test.go
server/services/v1/auth/gotrue.go
server/services/v1/auth/gotrue_test.go
server/services/v1/auth/provider.go
test/docker/docker-compose.yml
test/v1/server/auth_test.go

- Disabled token cache for gotrue implementation of oauth provider.
- Replaced LRU token validation cache with LRU+expiring token validation cache.
- Added a special header that allows us to bypass token validation cache.
- Added test that exercises token validation with and without cache.
Added tests.

Auth caches refactor

---

schema/rules.go
schema/rules_test.go

fix: Detect incompatible schema changes in nested fields

---

schema/rules.go

Nested fields checks were missing.

fix: Check nested fields for backward compatibility check for search

---

server/metadata/tenant_test.go
store/kv/base.go
store/kv/fdb.go
store/kv/kv.go
store/kv/kv_store.go
store/kv/kv_test.go
store/kv/measure.go
store/kv/noop_store.go

Remove unused interfaces from KV.
Our test suite makes sure Tigris works the same way as before.
This was discovered while working on #918

feat: remove unused kv interfaces

---

api/server/v1/search.go
api/server/v1/validator.go
test/v1/server/search_test.go

Add more request validation rules for search indexes

chore: Add more request validation rules for search

---

api/server/v1/validator.go
server/services/v1/search/errors.go
server/services/v1/search/runner.go
server/services/v1/search/session.go
test/v1/server/search_test.go

Reload metadata version in case of search index not found

fix: Reload version in case of index not found

---

go.mod
scripts/install_go.sh

Upgrade Go to 1.20.2

---

schema/collection.go
schema/collection_test.go
schema/fields.go

Allow sub-objects with arbitrary properties.

Allow maps in schema

---

.github/workflows/cli-test.yaml
test/v1/cli/backup.sh
test/v1/cli/import.sh
test/v1/cli/main.sh
test/v1/cli/scaffold.sh
test/v1/cli/search/import.sh

Update CLI tests

---

.github/workflows/test-docker-local-image.yaml

Fix local image test workflow

---

server/main.go
server/muxer/muxer.go
server/services/v1/database/search_indexer.go
server/services/v1/service.go
store/kv/chunk.go
store/kv/chunk_test.go
store/kv/fdb.go
store/kv/kv.go
store/kv/listener.go
store/kv/listener_store.go
store/kv/measure.go
test/v1/server/document_test.go
test/v1/server/integration_test.go

refactor: Move listener out of FDB and move it at the top of chain

---

schema/fields.go
server/metadata/collection.go

Two code improvements I missed in #974

chore: Code improvements on collection metadata

---

server/services/v1/database/sessions.go
store/search/errors.go

Retry on search schema update race

---

.github/workflows/go-test.yaml
Makefile
api/server/v1/marshaler.go
api/server/v1/marshaler_test.go
config/server.test.yaml
server/metadata/metadata.go
server/services/v1/user_metadata_provider.go
store/search/errors.go
test/docker/Dockerfile
test/docker/docker-compose.yml
test/v1/server/auth_test.go
test/v1/server/integration_test.go
test/v1/server/management_test.go

* Fix `make local_test`
* Fix repeatablility of the tests
* Add user and namespace metadata integration tests
* Refactor custom marshalling and add tests
* Count coverage from tigris_server2

Improve tests

---

api/server/v1/error.go
api/server/v1/error_test.go
query/filter/logical.go
query/filter/logical_test.go
server/search/facets.go
server/search/facets_test.go
server/services/v1/search/reader.go

TigrisError tests added

---

.codecov.yml
Makefile
README.md

Add codecov badge

---

.codecov.yml

Set the coverage target as 75%

Increase the coverage target

---

api/server/v1/tx.go
server/request/request.go
server/services/v1/management.go
test/v1/server/management_test.go

Implemented a management API to get the namespace information and consolidated list/info/describe into single API.
Added tests for it.

feat: Namespace API list/info/describe consolidation. 

---

schema/rules.go

Allow UUID as id type for search document

---

server/metrics/global_status.go
server/metrics/global_status_test.go
server/metrics/measurement.go
server/metrics/requests.go
server/services/v1/billing/event.go
server/services/v1/billing/metronome.go
server/services/v1/billing/metronome_test.go
server/services/v1/billing/noop.go
server/services/v1/billing/provider.go
server/services/v1/database/search_runner.go
server/services/v1/management.go
server/services/v1/search/runner.go
store/search/measure.go
store/search/search.go
store/search/ts.go

Report usage based metric in global status for most search operations (not all of them are covered yet). 
Tests included, the units are also exported as prometheus metrics.
#918

feat: initial implementation of search tracking in global status

---

cmd/consistency/consistency.go
cmd/consistency/workload/document.go
cmd/consistency/workload/queue.go
cmd/consistency/workload/workload_ddl.go
cmd/consistency/workload/workload_drop_create_write.go
cmd/consistency/workload/workload_insert.go
cmd/consistency/workload/workload_replace.go
cmd/consistency/workload/workload_search.go
cmd/consistency/workload/workload_small_load.go
server/services/v1/database/errors.go
server/services/v1/database/sessions.go
server/services/v1/search/indexer.go

- Add a small tool to generate/validate traffic on a standalone search index
- Fix a bug when the user schema has `id` field as an integer, but the field is not an index id.

fix: Add small tool for search index, fix a bug with integer id(non document id field)

---

server/config/options.go
server/metrics/measurement.go
server/metrics/metrics.go
server/metrics/secondary_index.go
server/metrics/secondary_index_test.go
server/services/v1/database/secondary_index_measure.go
server/services/v1/database/secondary_index_reader.go
server/services/v1/database/secondary_indexer.go
server/services/v1/database/secondary_indexer_test.go

Add metrics to secondary indexes
All current tests should pass
closes #1029

feat: add metrics to secondary indexes

---

server/services/v1/database/query_runner.go
test/v1/server/secondary_index_test.go

Adds range and the field used for the secondary index in the explain response

feat: add range and field used for the query in explain

---

go.mod
server/config/options.go
server/main.go
server/metadata/dictionary.go
server/metadata/dictionary_test.go
server/metadata/namespace.go
server/metadata/tenant.go
server/metrics/global_status.go
server/metrics/global_status_test.go
server/quota/namespace.go
server/services/v1/billing/event.go
server/services/v1/billing/metronome.go
server/services/v1/billing/noop.go
server/services/v1/billing/provider.go
server/services/v1/billing/reporter.go
server/services/v1/billing/reporter_test.go

- Usage reporter for periodically publishing metrics to billing service
- Unit tests
- Running tigris locally with proper metronome config
TIG-1204

feat: Usage reporter

---

server/metadata/namespace.go
server/metadata/tenant.go
server/search/hits.go
server/search/hits_test.go
server/services/v1/billing/metronome.go
server/services/v1/billing/reporter_test.go

chore: lint fixes

---

server/services/v1/billing/reporter.go

- Logs for debugging reporter in dev

fix: logs for debugging reporter

---

server/metadata/dictionary.go
server/metadata/tenant.go

- Tenant manager was getting a deadlock

fix: removing deadlock in tenant

---

config/server.dev.yaml
config/server.test.yaml
server/main.go

Respect configured log level

---

scripts/install_go.sh

Update Go to 1.20.3

---

server/metadata/tenant.go
server/metrics/measurement.go
server/metrics/metrics.go
server/metrics/metronome.go
server/metrics/metronome_test.go
server/services/v1/billing/metronome.go
server/services/v1/billing/metronome_test.go
server/services/v1/billing/reporter.go

- Capture and report latency and http responses from Metronome
- unit tests
TIG-1239

feat: Operational metrics for metronome integration

---

.github/workflows/cli-test.yaml
.github/workflows/go-test.yaml
.github/workflows/push-docker-image.yaml
.github/workflows/push-docker-local-image.yaml
.github/workflows/test-docker-local-image.yaml

Enable tests on merge_group event

---

server/services/v1/namespace_metadata_provider.go
server/services/v1/user_metadata_provider.go

Added additional logging to observe with ease

refactor: Added additional logging to observe with ease

---

server/metrics/measurement.go
server/metrics/requests.go
server/middleware/measure.go

Report usage metrics only per tenant instead of per tenant, per branch, per db, per collection and per grpc method.
Check the emitted metric tags.

feat: usage metrics only per tenant

---

server/metrics/measurement.go
server/metrics/metronome.go
server/services/v1/billing/metronome.go
server/services/v1/billing/metronome_test.go
server/services/v1/billing/reporter.go

- Renaming metrics for metronome
- Removing extra logs
- Recording metronome latency 
- Unit tests

fix: Fixing metric tags and recording latency

---

.github/workflows/cli-test.yaml
.github/workflows/go-test.yaml
Makefile

Remove temporary fix for Go version in actions

---

internal/data.go
query/filter/filter.go
query/filter/like.go
query/filter/logical.go
query/filter/selector.go
server/services/v1/database/row_reader.go
test/v1/server/secondary_index_test.go

This replaces the combining metadata in the json doc and keeps it as a separate field when checking the filters
All current tests should pass

fix: check metadata in filters

---

server/main.go
server/muxer/muxer.go
server/services/v1/billing.go
server/services/v1/billing/metronome.go
server/services/v1/billing/metronome_test.go
server/services/v1/management.go
server/services/v1/service.go

- Stub for billing service
- function `GetInvoices` and `GetInvoiceById` implementation in the metronome provider
- Unit tests
```shell
$ ➔  http GET localhost:8081/v1/billing/invoices/123
HTTP/1.1 501 Not Implemented
Content-Length: 97
Content-Type: application/json
Date: Thu, 20 Apr 2023 17:55:33 GMT
Vary: Origin
{
"error": {
"code": "UNIMPLEMENTED",
"message": "list invoices is not yet implemented on the server"
}
}
```
- TIG-1299

feat: billing service with Invoicing api

---

server/metadata/tenant.go
server/metadata/tenant_test.go
server/services/v1/billing.go
server/services/v1/billing/metronome.go
server/services/v1/billing/metronome_test.go
server/services/v1/service.go

Index size calculation

---

server/quota/storage.go

Fix crash in getting size statistics

---

server/services/v1/auth/gotrue.go

Added logging around app keys operations

refactor: Added logging around app keys operations

---

cmd/consistency/consistency.go
cmd/consistency/workload/document.go
cmd/consistency/workload/workload_compression.go
internal/data.go
internal/data.proto
server/config/options.go
store/kv/compression.go
store/kv/compression_test.go
store/kv/kv.go

Adding compression layer. The default compression used by this layer is the default zstandard mode(level 3) which is on the faster side. Compression is disabled right now and will be enabled through the config.

feat: Adding compression layer

---

server/services/v1/observability.go

Added more logs to get signals on metrics query failures.

refactor: Added logs on metrics query failures

---

server/config/options.go
server/metrics/global_status.go
server/middleware/measure.go
store/kv/measure.go

Configurable debug messages for metrics. 
Start tigris server locally with debug logging and see less metrics.

chore: configurable debug messages for all measurements

---

server/metrics/measurement.go
server/metrics/secondary_index.go

* Timer and histogram enabled was not processed for secondary indexes
* Removed double "_ok" and double "_time" from secondary index metric names
Enable secondary indexes with some traffic

chore: small secondary index metrics fixes

---

query/filter/key_builder.go
query/filter/key_builder_test.go
schema/collection.go
schema/queryable.go
server/services/v1/database/base_runner.go
server/services/v1/database/query_planner.go
server/services/v1/database/query_planner_test.go
server/services/v1/database/query_runner.go
server/services/v1/database/query_runner_test.go
server/services/v1/database/row_reader.go
server/services/v1/database/search_runner.go
server/services/v1/database/secondary_index_reader.go
server/services/v1/database/secondary_indexer.go
test/v1/server/document_test.go

- Refactoring query planner
- Honoring the sorting if it is on primary key fields
- Strictly enforcing sorting on a single field for database queries.

feat: Support sorting on primary key fields

---

server/services/v1/database/secondary_index_reader.go

fix: remove dbg print

---

schema/fields.go
server/metadata/collection.go
server/metadata/collection_test.go
server/metadata/tenant.go
server/services/v1/database/collection_runner.go
server/services/v1/database/secondary_index_measure.go
server/services/v1/database/secondary_indexer.go
server/services/v1/database/secondary_indexer_test.go
test/v1/server/collection_test.go
test/v1/server/secondary_index_test.go

Delete an index if the `index: true` is removed for that field in the schema. Also a smaller refactor of the collection metadata section.
Current tests should pass

feat: Delete removed indexes

---

server/services/v1/database/secondary_index_measure.go

Remove expensive instrumentation from secondary index iterator (creates a new tracing scope for each matching row).
Secondary index tests.
TIG-1404

chore: remove full instrumentation for secondary index iterator

---

server/config/options.go
server/metrics/measurement.go

Log method calls as an error which are longer than a threashold, so they can be investigated later.
Useful for debugging long requests.
TIG-1406

feat: log long method calls in the error log

---

server/metadata/namespace.go
server/metrics/global_status.go
server/metrics/measurement.go
server/middleware/measure.go
store/kv/measure.go
store/search/measure.go

Log the number of documents for slow calls
Unit tests
TIG-1406

feat: log the number of documents for a slow call

---

schema/collection.go
test/v1/cli/backup.sh
test/v1/cli/import.sh
test/v1/cli/main.sh

Recurse into arrays to allow nullable fields

---

api/server/v1/error.go
api/server/v1/marshaler.go
server/services/v1/api.go
test/v1/server/collection_test.go
test/v1/server/integration_test.go
util/util.go

[Server] Batch create collections API

---

server/metrics/datadog.go
server/metrics/datadog_test.go

tigris operation read, write are expanded to include other APIs. This PR updates the filtered method tags for read/write operation.
updated tests.

fix: Fixed metrics filtering for tigris_operation

---

server/main.go
server/services/v1/billing/reporter.go
server/services/v1/billing/reporter_test.go

- Report search index sizes to metronome
- local dry run
TIG-1423

feat: reporting search index sizes to metronome

---

server/services/v1/auth/user_manager.go
test/v1/server/auth_test.go

Added more fields to the invitation api response
Updated tests to look for it.

feat: Added more fields to the invitation api response

---

schema/schema.go
server/metadata/tenant.go
server/services/v1/api.go
server/services/v1/database/collection_runner.go
server/services/v1/database/database_runner.go
server/services/v1/database/sessions.go

Significantly improves application start time.

Better detection of unchanged schema

---

reviewpad.yml

Fix automerge of release PR

---

api/server/v1/marshaler.go

Avoid allocation and copy in custom unmarshal

---

server/main.go

Report server origin on start

---

api/server/v1/tx.go
server/middleware/authz.go
server/middleware/authz_test.go
server/services/v1/api.go
server/services/v1/auth/auth0.go
server/services/v1/auth/gotrue.go
server/services/v1/auth/noop.go
server/services/v1/auth/provider.go
test/docker/docker-compose.yml
test/v1/server/auth_test.go
test/v1/server/integration_test.go

Global app keys allows machine to perform some global operations such as create/list/delete projects.
Added test for it.

feat: Added global app keys

---

schema/fields.go
server/metadata/tenant.go
server/services/v1/api.go
server/services/v1/database/collection_runner.go
server/services/v1/database/indexer_runner.go

Adds a new index building state to show an index is in the process of being built.
With the collection describe method, Tigris looks to see if there are no indexes and then upgrades the colleciton. No indexes are legacy collections that need to be updated.

fix: Add new index building state

---

test/v1/server/auth_test.go

- Added more test to cover the invitation apis.
- Updated tests to follow newer invitation api behavior. (singular invitation for same email/namespace).
Note: this is expected to succeed after the next release of gotrue.

fix: Added more test to cover the invitation apis

---

server/metadata/tenant.go
server/metrics/datadog.go
server/metrics/datadog_test.go

Convert metrics tags to lower case before querying.
Added test for it.

fix: Sanitize the metrics input to match what is ingested

---

server/config/options.go
server/middleware/auth.go

fix: Added more log to auth failures

---

server/services/v1/billing/metronome.go

- Retructuring duration recording
- Unit tests
-

fix: finish tracing once metrics are recorded

---

server/services/v1/auth/user_manager.go

While querying users for a namespace. Look into accessibleNamespaces for users.
Tested it on auth0 query.

fix: Update search query to look into accessibleNamespaces for user

---

query/filter/key_builder.go
query/filter/key_builder_test.go
schema/collection.go
schema/queryable.go
schema/queryable_test.go
schema/search.go
server/services/v1/database/query_planner.go
server/services/v1/database/search_indexer_test.go
server/services/v1/database/secondary_index_reader.go

Remove generics from key builder
`make test`
Fixes #1027 
Related Discord discussion thread - https://discord.com/channels/1033842669983633488/1033843208192524348/1095960587806183494

Remove generics from key builder

---

server/services/v1/auth/user_manager.go

Use search api to list users.
Testing on dev cluster.

fix: Fixed user search

---

store/kv/stats.go

fix: Wrap properly kv stats error

---

server/services/v1/auth/gotrue.go
server/services/v1/auth/user_manager.go
test/v1/server/auth_test.go

Dry user invitation verification (without accepting)
Added test.

feat: Dry user invitation verification (without accepting)

---

server/metrics/measurement.go
server/metrics/measurement_test.go
server/middleware/measure.go

Add error status to long request log
Tested locally

feat: add error status to long requests

---

server/services/v1/database/base_runner.go
server/services/v1/database/search_indexer.go
server/services/v1/database/search_indexer_test.go

Sanitize array of objects by removing nulls before sending to search

fix: Sanitize array of objects by removing nulls before sending to search

---

server/services/v1/api.go

Check the metadata version before reads in case an index schema has been updated.

fix: check metadata version before reads

---

query/filter/filter.go
query/search/search.go
server/services/v1/database/query_runner.go
server/services/v1/database/search_reader.go
store/search/ts.go

For read queries, only use the indexing store for sorting.

refactor: Only use indexing store for sorting results

---

server/services/v1/workers/worker.go

Fix missing collection causing workers to crash

fix: check for missing collection

---

server/metrics/measurement.go
server/metrics/requests.go
server/middleware/measure.go
server/services/v1/workers/worker.go

Latest Beta

---

server/services/v1/workers/worker.go

Catch panics from background workers

fix: catch background worker panics

---

api/server/v1/marshaler.go

- /billing/invoices was a GET endpoint, changed it to POST
- Custom unmarshaling of JSON

fix: change /billing/invoices endpoint to be a POST from GET

---

server/config/options.go
server/metadata/tenant.go
server/services/v1/database/search_runner.go

Add configurable log for collection search filter

chore: Add configurable log for collection search filter

---

api/server/v1/header.go
server/request/request.go
server/services/v1/database/search_indexer.go

fix: Allow to disable search indexing

---

server/services/v1/billing.go
server/services/v1/billing/reporter.go

fix: metronome nil check before using

---

api/server/v1/marshaler.go
api/server/v1/marshaler_test.go

- fix: Marshaling invoice response
- fix: Marshal usage response properly
- Unit tests

fix: Marshaling JSON responses for billing APIs

---

api/server/v1/tx.go
server/middleware/authz.go
server/middleware/authz_test.go

Update authz for search methods
updated unit tests.

fix: Update authz for search methods

---

server/services/v1/billing/reporter.go

- Logging to figure out invalid namspaceId
- Logging message changes only

fix: Moving namespace meta nil up a level

---

server/metrics/global_status.go

fix: Fix search write units

---

api/server/v1/tx.go
server/middleware/authz.go
server/middleware/authz_test.go

Update authz for billing + observability methods. Owner should be able to get access to billing methods.
updated tests.

fix: Update authz for billing + observability methods

---

server/middleware/authz.go
test/docker/docker-compose.yml

Gotrue container's newer release moved the file paths from `/home/netlify/*` to `/home/tigris/*`. This change updates the relevant configuration.

fix: Fixed auth test container configuration

---

server/metrics/measurement.go
server/metrics/requests.go
server/quota/storage.go

Emit search write metrics as well
Look at the emitted metrics

feat: search write metrics

---

server/metadata/tenant.go
server/services/v1/api.go
server/services/v1/database/collection_runner.go
server/services/v1/database/sessions.go
server/transaction/manager.go

Do not reload metadata if nothing changed in describeCollection

fix: Do not reload metadata if nothing changed in describeCollection

---

server/services/v1/database/search_runner.go

Only log when needed for filters

fix: More accurate logging(non empty filters)

---

test/v1/server/server_test.go

```
http://tigris_server:8081/http://tigris_server:8081/v1/observability/info
```
fixes this URL in the test.

fix: Fixed TestInfo test

---

server/metadata/tenant.go
server/services/v1/api.go

A single transaction is hitting the 5-second limit now, so we need to split reload on independent transactions.

fix: Break up tenants reloading on independent transactions

---

server/services/v1/auth/gotrue.go

fix: Reduce log noise

---

api/server/v1/marshaler.go
api/server/v1/tx.go
config/server.test.yaml
server/config/options.go
server/middleware/auth.go
server/middleware/auth_test.go
server/middleware/authz.go
server/middleware/authz_test.go
server/services/v1/auth/auth0.go
server/services/v1/auth/gotrue.go
server/services/v1/auth/gotrue_test.go
server/services/v1/auth/noop.go
server/services/v1/auth/provider.go
server/services/v1/observability.go
test/v1/server/auth_test.go
test/v1/server/integration_test.go

Implemented API key authentication mechanism.
Implemented WhoAmI API.
Added tests.

feat: Implemented API key authentication mechanism

---

.golangci.yaml
cmd/consistency/workload/document.go
server/config/options.go
server/services/v1/auth/gotrue.go
server/services/v1/database/query_runner.go
util/log/log.go

chore: Disable depguard, nakedret and fix tagalign linters

---

.github/workflows/push-docker-arm64.yaml

fix: Disable arm64 build

---

server/config/options.go
server/services/v1/auth/user_manager.go

Put user invitation methods behind config

feat: Put user invitation methods behind config

---

server/muxer/grpc.go
server/muxer/http.go
test/v1/server/unix_test.go
util/util.go
util/util_darwin.go
util/util_linux.go

Fix peer credentials call on Darwin

---

server/config/options.go
server/metadata/tenant.go

This reverts commit efc7cecca2427d0d9b73d306f0d65f0189cdfc7c.

Revert "fix: Skip reloading certain search indices (#1270)"

---

server/config/options.go
server/metadata/tenant.go

This reverts commit 2a4f4088e9d334d3a44c7d587204ffc588d41d83.

Revert "Revert "fix: Skip reloading certain search indices (#1270)" 

---

server/metadata/tenant.go

Do not panic on search failures during start time

fix: do not panic on search failures during start time
